### ISSUE TITLE
Unused import missing underline and tooltip line for second (and following) import in a group

### ISSUE THREAD

**Issue by peddermaster2** [rust-lang/rls-vscode#106]
### Steps to reproduce
- (Create and) open a rust project in VSCode
- In an empty lib.rs/main.rs file add one `use` statement with a group of two or more unused imports like this
```rust
use std::fmt::{Display, self};
```
- Wait for RLS to finish the analysis
- Hover over each import to see their tooltip

### Expected
- Both / all unused imports are underlined
- Both / all unused imports show a line in their tooltip like `[rustc] unused import <import>`

### Actual
- The first unused import has a underline, the second (and following) do not
- The first unused import shows a line in its tooltip like `[rustc] unused imports <import1>, <import2>`

See the attached screenshots

![rust_rls_missing_marker_on_second_unused_import](https://user-images.githubusercontent.com/1105042/28993977-41732212-79c3-11e7-9105-764855d1c095.png)
![rust_rls_missing_marker_on_second_unused_import_2](https://user-images.githubusercontent.com/1105042/28993980-4723b10e-79c3-11e7-963e-f76ae6eeb52c.png)

### Information of the setup
- rls 0.1.0-nightly (cb8a590 2017-08-02)
- rustc 1.21.0-nightly (1d2a6df38 2017-08-03)
- VSCode extention: rust-lang.rust 0.1.0 (custom compile with 7630c5e0e68c2f85cd48c30aea4c6937bda27e7e)
- VSCode: 1.14.2

**Comment by Xanewok** [comment]
The underline is now present for all the unused import entries.
