### ISSUE TITLE
deglob adds unused imports

### ISSUE THREAD

**Issue by fabricedesre** [rust-lang/rls-vscode#116]
Starting with a snippet like:

```rust
use chrono::prelude::*;

let now: DateTime<Utc> = Utc::now();
println!("{:?}", now));
```
and using the `deglob` command, the result is:

```rust
use chrono::prelude::{TimeZone, Utc, DateTime};
```

where `TimeZone` is not needed, and actually detected as such by rls :)

**Comment by nrc** [comment]
This is probably a bug in the compiler, but I'll track it here, since it won't have an effect outside of the RLS.

**Comment by jonasbb** [comment]
I found a case in which deglob adds imports which are not available. It occurs with an up-to-date rustc (rustc 1.24.0-nightly (0a2e9ade8 2017-11-29)) and self-compiled current rls.

I have a minimal example. 

```rust
#[macro_use]
extern crate failure;

use failure::*; // -> use failure::format_err;

fn main() {
    let _ = format_err!("Msg");
}
```

This results in this error message:

```
error[E0432]: unresolved import `failure::format_err`
 --> src/bin/test.rs:4:5
  |
4 | use failure::format_err;
  |     ^^^^^^^^^^^^^^^^^^^ no `format_err` in the root

warning: unused import: `failure::format_err`
 --> src/bin/test.rs:4:5
  |
4 | use failure::format_err;
  |     ^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default
```

**Comment by nrc** [comment]
Interesting! I think this is correct if you opt-in to macros 2.0 (`feature(decl_macros)` or something like that), but I assume you have not done that because you are using `#[macro_use]`. I guess this is a compiler bug (there are known issues around glob imports and macros 2.0).

**Comment by Xanewok** [comment]
I can't reproduce either; macro imports work fine under edition 2018 and a lot of work has been put for it to work nicely with name resolution, so I'd assume this works fine now. Please reopen if this is still an issue.
