### ISSUE TITLE
Formating and building issues

### ISSUE THREAD

**Issue by k0pernicus** [rust-lang/rls-vscode#122]
My `code` version: `Version 1.15.0 (1.15.0)`.

After a clean installation of `rls-vscode` (0.2.1.), I don't have build outputs because it seems `rustfmt` is crashing all the time:
```
[Error - 7:59:20 PM] Request textDocument/formatting failed.
Message: Reformat failed to complete successfully
Code: -32603 
```

If I set `editor.formatOnSave` to `false`, the plugin seems working.
Otherwise, if I put an error in my program (for example a `let` statement without semi-colon), the analysis runs but no errors have been found...

My `$HOME/.cargo/bin` contains `racer` and `rustfmt`, which have been properly set.

I am using those parameters:
```
"editor.formatOnSave": true,
"rust.build_lib": true,
"rust.cfg_test": true,
"rust.show_warnings": true,
```

For the `rustfmt` error, I think it is related to #65.
For the build issue... I really don't know.

**Comment by nrc** [comment]
Hmm, I imagine if formatting is crashing every time we might not get a chance to build? I've been meaning to fix the rustfmt bug here, hopefully that will fix things.

> My $HOME/.cargo/bin contains racer and rustfmt, which have been properly set.

You don't need racer and rustfmt separately installed - the RLS brings its own versions. It shouldn't cause problems though.

**Comment by k0pernicus** [comment]
Hi @nrc - thank you for the response!
Sorry for the delay, my laptop crashed so...
I will try again to install it as soon as I recover it.

**Comment by Xanewok** [comment]
Integration with Rustfmt has improved in the recent RLS and I can't reproduce this issue. Please reopen if that's still the case.
