### ISSUE TITLE
detected cargo tasks aren't showing up in ctrl-shift-b ("Tasks: Run Build Task") and similar

### ISSUE THREAD

**Issue by radix** [rust-lang/rls-vscode#193]
I have a project that already has a tasks.json. I discovered that rust-rls automatically provides some tasks for cargo projects (build, run, test, clean), and I can reach these tasks with ctrl-alt-t ("Tasks: Run Task"). However, when I invoke "Tasks: Run Build Task" (with ctrl-shift-b), I don't see that task: I only see one that I have from my tasks.json file. In another project which doesn't have a tasks.json file, I do see this detected task.

Another notable difference is that the project which isn't showing the build task with ctrl-shift-b is also a multi-crate workspace, in case that matters.

**Comment by nrc** [comment]
I don't recall exactly where we landed with this, but I think that if the user has a tasks.json, then we will not overwrite that with our own tasks. So this might be expected behaviour.

**Comment by radix** [comment]
well yeah, I would not expect anything to overwrite tasks.json, just that both my tasks and the auto-detected tasks would both appear in the list (that's how "Tasks: Run Task" works). but maybe this is a vscode bug instead of a rls-vscode bug?

**Comment by Xanewok** [comment]
Tasks were revamped recently and should be properly auto-detected now.
