### ISSUE TITLE
Feature request: add tooltip for method arguments

### ISSUE THREAD

**Issue by peperunas** [rust-lang/rls-vscode#199]
Hello!

It would be great to have a tooltip which helps you remember which argument has to be passed to a method.

This is what I mean (taken from a `.c` source file):

![Tooltip example](https://user-images.githubusercontent.com/6033387/33278356-960a8d42-d39b-11e7-9ff3-304d1352ab3c.png)

Keep up the good work!

**Comment by nrc** [comment]
We already have this information - we display it on hover of the function name, so we'd just need to surface that as a tooltip. I assume there is an LSP message for that, though I don't know what that is.

**Comment by jonasbb** [comment]
I think this is tracked as https://github.com/rust-lang-nursery/rls/issues/97I don't think it is an easy issue. 

The LSP message would be
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_signatureHelp

**Comment by nrc** [comment]
I was thinking there might be an easier solution than full signature help - just pop up a tooltip quoting the function signature when the cursor is in function parens. Not sure if that is possible, but if it is, then it would be much easier.

**Comment by viktorstrate** [comment]
In Javascript and other languages, I can press <kbd>⌘</kbd>+<kbd>Shift</kbd>+<kbd>Space</kbd> to call the `Trigger Parameter Hints` command, which I find extremely useful. But it doesn't work with this plugin.

The shortcut is only activated when `editorHasSignatureHelpProvider` is true.

Is there any updates on this issue?

**Comment by radu-matei** [comment]
If anyone is interested in this feature, have a look at #552.
Feedback appreciated, thanks!

**Comment by jens1o** [comment]
Thanks for your work!
I wonder whether it would be possible to syntax highlight the signature help, like it is when hovering the method?

**Comment by radu-matei** [comment]
@jens1o -- Unfortunately, the type of the label in the signature help object is a plain string, so we have to strip the markdown formatting of the function signature, meaning it's just plain text (this is how all other extensions that add VS Code language support display the signature help label).

**Comment by jens1o** [comment]
Okay, that's disappointing, but thanks for your work! :)

**Comment by radu-matei** [comment]
If VS Code gets an update on the label, we can also change it -- but otherwise, I don't think there's much we can do here about the formatting.

That being said, there are things we can improve -- around highlighting the current parameter -- but for this, we need to use the signature help request with the RLS, which is not currently implemented.

Do we want to keep this issue open for that, or now that [0.6 has been released](https://github.com/rust-lang/rls-vscode/releases/tag/0.6.0) we can close it?

**Comment by Xanewok** [comment]
I think we can close this now, yeah. Thanks again @radu-matei for all the hard work!
