### ISSUE TITLE
Selecting a word does not use semantic info for higlighting

### ISSUE THREAD

**Issue by nrc** [rust-lang/rls-vscode#2]
Putting the cursor in a word does, but actually selecting the word does not

**Comment by 0x7CFE** [comment]
Isn't it intended behaviour? AFAIK KDevelop does exactly this: when you select something, it highlights all occurrences of that particular character sequence, whether putting cursor over syntax element highlights only semantics.

**Comment by jonathandturner** [comment]
This uses the default behaviour for VSCode.  I'd rather we just use what they recommend rather than rolling our own.

**Comment by Xanewok** [comment]
Triage: Gonna close this as 'working as intended'.
