### ISSUE TITLE
Vscode doesn't show syntax error introduced into file

### ISSUE THREAD

**Issue by starrhorne** [rust-lang/rls-vscode#206]
When I open a rust file in VSCode it completes the initial syntax check successfully. However, subsequent syntax checks fail to update the UI. If I introduce bad syntax into the file, it's not flagged in the UI. 

Interestingly, when I view the logs it seems that RLS is identifying the syntax error and reporting it, but that information isn't causing the Problems menu to be updated. 

Here's a [video](https://www.dropbox.com/s/5gm5eaesoiopbym/vscode.ogv?dl=0) which shows this behavior (it starts at around 00:30). Here is the logfile set with rls=trace: [rls1512169060792.log](https://github.com/rust-lang-nursery/rls-vscode/files/1523252/rls1512169060792.log)

There's a chance something specific to my codebase may be triggering the problem. I'm not able to reproduce the problem on a bare-bones project. [Here's the repo ](https://bitbucket.org/snhorne/nes-rust/overview)in question. Feel free to clone for testing if you need to. 

```
$ rls -V
rls-preview 0.124.0-nightly (194f828 2017-11-27)

$ rustc -V
rustc 1.24.0-nightly (23032d0af 2017-11-30)

$ code -v
1.18.1
929bacba01ef658b873545e26034d1a8067445e9
```

**Comment by sfackler** [comment]
I'm seeing this more generally as rls not responding anymore after the initial analysis.

**Comment by reynoldsbd3** [comment]
Same here. RLS is generating plenty of output, none of which is being picked up by the extension and reported

**Comment by reynoldsbd3** [comment]
Update on this: after successfully building my project, "problems" started getting picked up and reported (via "Problems" pane and red/green squiggles in editor).

So it appears that at least one successful build is required before things start working correctly. Unsure whether that indicates a problem with the extension, RLS, or VSCode itself...

**Comment by starrhorne** [comment]
FWIW this issue seems to not happen if I use nightly-2017-11-01

**Comment by ivanovaleksey** [comment]
I got the same issue. Though sometimes everything is fine but sometimes I got errors in Output window and no notifications in editor. I can't detect exactly why it works or not.

**Comment by Xanewok** [comment]
This is most likely a symptom of a deadlocked RLS instance. Generally we improved a lot since the time it reported and we surface more errors to the user now. As such, I think we can close the issue but please reopen if you encountered this more recently.
