### ISSUE TITLE
No typechecking in main.rs if lib.rs exists

### ISSUE THREAD

**Issue by fenduru** [rust-lang/rls-vscode#211]
Steps to reproduce:

1. Create new project with `cargo new --bin test-project
2. Edit main.rs - observe typechecking/linting occurs in main.rs
3. Create lib.rs - observe typechecking/linting does not occur in lib.rs
4. Restart RLS from command menu
5. Typechecking now only shows up in lib.rs, no longer main.rs

**Comment by jonasbb** [comment]
This feature is currently behind the unstable feature flag. You could try setting `workspace_mode` and `unstable_features` to true, as documented in the configuration section https://github.com/rust-lang-nursery/rls#configuration

**Comment by Xanewok** [comment]
The workspace mode is on now by default and both of the cases work nowadays (breaking `lib.rs` retains diagnostics in `main.rs` and it can lint it separately), so closing.
