### ISSUE TITLE
Put progress of operations into the VS Code Output window

### ISSUE THREAD

**Issue by TomasHubelbauer** [rust-lang/rls-vscode#215]
Please consider creating an Output window channel for this extension where nightly toolchain installation stdout and RLS installation stdout would be redirected to. It went through fine for me, but I would like to see what's happening and I think overall it would increase transparency in a useful way.

**Comment by mcclure** [comment]
Is there some way I can "bump" this issue?

I am currently installing this vscode extension on the free wifi on a train… the download rates are very poor… it has been going for some time, over an hour… the bottom of VS Code is spinning "Installing Toolchain"… I do not have any way of knowing how much progress it is making… I have no way of knowing if it has stalled out… I have no way of knowing if it is safe to quit *_*

If I could see what commands were being run, I'd at least have a clearer sense of "oh, it's got another three hours to go" vs "oh, i should quit this and try it again on better wifi…"

**Comment by nrc** [comment]
I think this would be great to implement, but I don't have the bandwidth to do it myself right now, sorry. Happy to review and/or mentor if someone wants to work on a PR.

**Comment by TomasHubelbauer** [comment]
The code which deals with installing the toolchain is in [`rustup.ts` at line 78](https://github.com/rust-lang-nursery/rls-vscode/blob/master/src/rustup.ts#L78). It uses the [`execChildProcess` helper](https://github.com/rust-lang-nursery/rls-vscode/blob/master/src/utils/child_process.ts#L25), which in turn uses `child_process.exec` which buffers `stdout` and `stderr` until the proces terminates. To be able to see stdout and stderr events as they are emitted, we should introduce a new helper for `child_process.spawn` which is an `EventEmitter` so we then can use something like:

```ts
import * as childProcess from 'child_process';
const process = childProcess.spawn(…);
process.stdout.on('data', …);
process.stderr.on('data', …);
process.on('exit', …);
```

I will take a look at surfacing these messages back to `tryToInstallToolchain` and keeping an Output pane  channel synced with them as well as displaying the latest line as the *Installing toolchain* spinner suffix. Off the top of my head I don't know whether the spinner is clickable, either way, I'll try to make it so that it opens the Output channel up.
