### ISSUE TITLE
RLS could not set RUST_SRC_PATH for Racer on Windows

### ISSUE THREAD

**Issue by nitzanms** [rust-lang/rls-vscode#224]
I'm trying to start VSCode with Rust (rls) extension, but RLS server fails with the error:
RLS could not set RUST_SRC_PATH for Racer because it could not read the Rust sysroot.

![image](https://user-images.githubusercontent.com/464489/34640183-9168c00e-f2f6-11e7-8fde-b481711fe997.png)

**Comment by nitzanms** [comment]
I looked at https://github.com/rust-lang-nursery/rls-vscode/issues/167 but the solutions offered there didn't resolve the issue.

Reinstalling the nightly toolchain myself fixed this.

**Comment by jonasthewolf** [comment]
I had the same issue on Windows and Rust (rls) extension 0.3.2.
I had the stable toolchain installed, but the ‚rust-client.channel’ was set to ‚nightly‘.
Fixing this, solved the issue for me.

**Comment by driftluo** [comment]
The same issue for me on Win10, but not on Ubuntu.

**Comment by RileyRedpath** [comment]
Had the same issue, starting vscode as an admin fixed it for me.

**Comment by fedorg** [comment]
If you are using a specific nightly toolchain version (i.e. nightly-2019-01-01) because the [latest nightly is missing the rls altogether](https://mexus.github.io/rustup-components-history/), specifying the exact version in settings.json might help.
```
{
    "rust-client.channel": "nightly-2019-01-01"
}
```

**Comment by Junzki** [comment]
> If you are using a specific nightly toolchain version (i.e. nightly-2019-01-01) because the [latest nightly is missing the rls altogether](https://mexus.github.io/rustup-components-history/), specifying the exact version in settings.json might help.
> 
> ```
> {
>     "rust-client.channel": "nightly-2019-01-01"
> }
> ```

It works for me on mac as the plugin has not specified `rust-client.channel`.

**Comment by swayson** [comment]
Setting VSCode user config as follows, worked for me.
```
{
    "rust-client.channel": "stable"
}
```

rustc 1.33.0 (2aa4c46cf 2019-02-28)
OS: Windows 10
Rust (rls) Version: 0.5.3

**Comment by Xanewok** [comment]
cc #522

**Comment by Xanewok** [comment]
We warn against wrongly detected sysroot and RUST_SRC_PATH detection is now done solely by Racer, so closing this.
