### ISSUE TITLE
Can RLS do a better job of autodetecting rust.build_bin? 

### ISSUE THREAD

**Issue by masonk** [rust-lang/rls-vscode#229]
Let me start by thanking you for an excellent tool that's, overall, dramatically improving my Rust experience!

That said, it took me about an hour to figure out that the reason why I'm not getting tooltips and error squiggles on one of my source files is that the extension does not detect the bin crate that I'm currently editing for analysis. Wouldn't it be best to run analysis on any bins that have an open source file and to remove this configuration option entirely?

If that is technically infeasible, here are few other possibilities that I think would have been a better default experience than the hard wall that I just encountered:

1. A notification warning me that the current source file isn't being analyzed and giving me the solution.
2. Default rust.build_bin to analyze all bin crates in `Cargo.toml`.

The [repo](https://github.com/masonk/advent2017) where I encountered this is strangely laid out, because I started it before I understood how Cargo works. But I can't think of any good reason why RLS wouldn't be able to support this kind of project layout.

Finally, now that I know what the issue is, I don't see a great workaround. Every time I switch bins, it looks like I'll have to go to the preferences and manually update my `rust.build_bin` setting to the new crate.  Could this setting accept an array of builds, or an `:all` keyword?

**Comment by Xanewok** [comment]
Hey, glad it's useful!
For analyzing more crate targets, I believe initial build in the `workspace_mode` (on by default now) configuration should queue full package rebuild, including every `[[bin]]` target. What toolchain and/or RLS version are you using?
Currently `rust.build_bin` and `rust.build_lib` options work only with single package mode (`workspace_mode: false`).

**Comment by masonk** [comment]
When I turn on workspace mode and turn off build_bin, I do indeed get the squiggles. Performance seems comparable as well. So, thanks. However, based on my settings, it looks like workspace mode is not the default for my project, even though my Cargo.toml includes [workspace].

VSCode  1.19.2
Extension: Rust (rls) 0.3.1 - 2017-10-04 (the most recent available from my editor gui, AFAICT)


All applicable setting overrides in this VSCode workspace before changing to workspace mode. I don't think workspace was enabled by default.
```
{
    "rust-client.channel": "nightly",
    "rust-client.revealOutputChannelOn": "info",
    "rust.unstable_features": true,
    "rust.build_bin": "advent16",
    "editor.minimap.enabled": false,
    "editor.formatOnSave": true,
    "window.zoomLevel": 0,
    "workbench.activityBar.visible": true
}
```

```
PS C:\Users\mason_000\wsl\dev\rust\advent2017> rustup show
Default host: x86_64-pc-windows-msvc

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
beta-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
rustc 1.25.0-nightly (73ac5d6a8 2018-01-11)

PS C:\Users\mason_000\wsl\dev\rust\advent2017> rustup -V
rustup 1.9.0 (57fc3c087 2018-01-04)
```

**Comment by Xanewok** [comment]
We turned on workspace mode to be the default some time ago, I hope this is resolved now. Doing an issue triage so I'm going to close this, but please reopen if that's still an issue!
