### ISSUE TITLE
Terminal not reused by subsequent tasks

### ISSUE THREAD

**Issue by Clockwork-Muse** [rust-lang/rls-vscode#236]
Whenever a task is started, it opens, and never reuses, a new integrated terminal window:

![image](https://user-images.githubusercontent.com/5569508/35135933-32271a2a-fc95-11e7-874e-1567bc6d69c9.png)

This is mostly amusing at the moment, it doesn't appear to have much of a performance impact (even when there's been 50+ terminals).

**Comment by Xanewok** [comment]
The default is now to reuse the terminal, can confirm that the same terminal is being used for every invoked task now.
