### ISSUE TITLE
The "Parameter Hints" function cannot support words that are not from current project files or `use` something.

### ISSUE THREAD

**Issue by abc1236762** [rust-lang/rls-vscode#238]
This plugin support "Parameter Hints" function, for example : 

```rust
use std::io;

fn main() {
	let mut b = String::new();
	io::stdin().read_line(&mut b).expect("");
	println!("{}", b);
}
```
When my mouse touch `read_line`, the screen will show the hint that says `fn (&self, buf: &mut String) -> io::Result<usize>`.

But when my mouse touch these functions or micros ... that I can use without using `use` or `mod` to require them, like "`println!`" and "`new` function in  `String::new`" ..etc , "Parameter Hints" function will not work. Expect functions or micros ... that I defined in current project files.

**Comment by Xanewok** [comment]
Opened https://github.com/rust-lang/rls/issues/1419 to track, thankfully everything else besides macros is now properly linked (e.g. `new`, `String`).
