### ISSUE TITLE
Error squiggles will not update after run `Rust: cargo build`

### ISSUE THREAD

**Issue by abc1236762** [rust-lang/rls-vscode#239]
Normally, when my code have any errors that could be unbuildable, this plugin will tell me where are wrong with squiggles. But if I run `Rust: cargo build` driectly before I fix those wrong, those squiggles will not disappear after I fix those wrong. I must build again to make those squiggles be removed. 

For example:
```rust
fn main() {
	let a = 0;
	println!("{}", a);
}
```
When I commented `let a = 0;`, like:
```rust
fn main() {
	//let a = 0;
	println!("{}", a);
}
```
This plugin will use squiggle on editor to tell me that my code have a error on `a` in `println!("{}", a);` line that is `[rustc] cannot find value 'a' in this scope`.
But if I run `Rust: cargo build` driectly without fix this error on my code, then remove comment, like:
```rust
fn main() {
	let a = 0;
	println!("{}", a);
}
```
The squiggle on `a` in `println!("{}", a);` line will not be removed.
Of course, this code can be built without any errors. The squiggle on `a` in `println!("{}", a);` will be removed after this action.

**Comment by Xanewok** [comment]
Fixed in https://github.com/rust-lang/rls-vscode/commit/8c471d443179f267f8a0181890fdfc933fd385da, confirmed just now.
