### ISSUE TITLE
Using stable, everything stopped to work suddenly

### ISSUE THREAD

**Issue by Geobert** [rust-lang/rls-vscode#241]
As title said, yesterday, everything was working fine, and today, nothing work at all. No output window, RLS: done in status bar.

Win10, VSCode 1.19.3

**Comment by Geobert** [comment]
It is RLS related, tried the other Rust plugin (kalitaalexey.vscode-rust), same issue.

**Comment by Geobert** [comment]
Got an output: https://gist.github.com/Geobert/207b2fdae3b5ceca01bb025e90373dd0

**Comment by devvoid** [comment]
I'm having the exact same problem. Linux Mint 18.2, running VSCode 1.19.3. Any help would be much appreciated.

**Comment by Xanewok** [comment]
That looks really off... It seems that a stable rustc is somehow used to compile `clippy_lints-0.0.181`?
Do you have `rust-client.channel` set to `stable`?

**Comment by Geobert** [comment]
I was on `stable` when it stopped working.

I tried nightly as well.

I was on clippy 0.0.165 (for project reason, cobalt is on this version at the moment)

**Comment by alexreg** [comment]
Works on nightly for me, but not stable. (No debug output/problems, Mac OS X 10.13, "RLS: Done".) Any update? @nrc?

**Comment by nrc** [comment]
@Geobert, @alexreg I'm not clear on why Clippy is a thing here. Since Clippy only works on NIghtly, I would not expect it to work on stable, especially inside the RLS. But I'm not sure why the RLS is trying to compile it anyway.

What exactly are you trying to build? Does it work if you disable Clippy?

**Comment by alexreg** [comment]
@nrc Oh, I missed the comment on clippy. I don't think that applies in my case. For me, the issue is that "goto definition" and mouseover docs don't work (among a few other things).

**Comment by Geobert** [comment]
@nrc : even with `"rust-client.channel": "nightly",` it's not working at all.

the project [cobalt.rs](https://github.com/cobalt-org/cobalt.rs/) is the one I'm working on. In the file cobalt.rs, `build()` is the entry point, and it's calling some functions defined in the same file and it can't find their definition. 

try today with 0.4.0 of the vscode plugin and ` nightly-x86_64-pc-windows-msvc updated - rustc 1.26.0-nightly (259e4a678 2018-03-04)`

**Comment by alexreg** [comment]
For me it works with the nightly channel, I must be clear. It's just stable it doesn't work on.

**Comment by Geobert** [comment]
https://github.com/rust-lang-nursery/rls-vscode/issues/185#issuecomment-374772599

**Comment by Xanewok** [comment]
Stable RLS works with mouse hover and everything. Please reopen if there's still an issue with the stable channel.
