### ISSUE TITLE
execChildProcess does not work with wsl

### ISSUE THREAD

**Issue by kdy1** [rust-lang/rls-vscode#247]
https://github.com/rust-lang-nursery/rls-vscode/blob/5afe3bbe5b6cf538cafea9bf8bfe3b3779026041/src/utils/child_process.ts#L25-L40

For native windows binaries, this works well. But when wsl is involved (even if it's subprocess invoked from simple windows exe file) returned promise does not resolve because callback passed to `child_process.exec` isn't called. I'm not sure if this is an issue of rls-vscode, but this can be workarounded.

Also, I'm sure that command itself is invoked, because `stdout` is set to `nightly-x86_64-unknown-linux-gnu (default)` if I set timeout. (but timeout error occurs)

-----

When I modify definition like below and invocations, it works. 

```typescript

export async function execChildProcess(command: string, args: string[]): Promise<ExecChildProcessResult> {
    // FIXME: async
    const child = child_process.spawnSync(
        command, args, { encoding: 'utf8' },
    );

    if (child.error) {
        throw new Error(`Error running `${command}`: ${child.error}`);
    }

    if (child.status > 0) {
        throw new Error(`Error getting sysroot from `${command}`: exited with \`${child.status}\``);
    }

    if (!child.stdout || typeof child.stdout.toString !== 'function') {
        throw new Error(`Couldn't get sysroot from `${command}`: Got no ouput`);
    }

    return {
        stdout: child.stdout,
        stderr: child.stderr,
    };
}
```

So.. child_process.exec` seems like a root of issue. This should be replaced with `child_process.spawn` to work with wsl.

**Comment by yisonPylkita** [comment]
Yep, you are right. GH-335 will fix this issue

**Comment by yisonPylkita** [comment]
https://github.com/rust-lang/rls-vscode/pull/488 was merged a few days ago. Thus this bug should be fixed.

Do you mind running this extension from `master` to confirm the fix ?

**Comment by kdy1** [comment]
@yisonPylkita I uninstalled wsl for some reasons. So I can't.

**Comment by Xanewok** [comment]
This was done as part of the 0.6 refactor, closing this now.
