### ISSUE TITLE
'Find Implementations' not work

### ISSUE THREAD

**Issue by LJpgr** [rust-lang/rls-vscode#249]
I had installed this extension.When I excute 'Find Implementations' ,nothing happened,
and there was no  tips.
Please check this .
rustc version:1.23.0
vscode version :1.19.3
ext version :0.3.2

**Comment by Geobert** [comment]
https://github.com/rust-lang-nursery/rls-vscode/issues/241

**Comment by Xanewok** [comment]
Can't reproduce on the latest RLS master with
```rust
trait Bar {
    fn some_fn(mut arg: bool, arg1: u32) {}
}

struct Foo;
struct Another;

impl Bar for Foo {
    fn some_fn(mut arg: bool, arg1: u32) {

    }
}

impl Bar for Another {
    fn some_fn(mut arg: bool, arg1: u32) {

    }
}
```

Go to Implementation on `Bar`, `Foo`, `Another` works as expected
