### ISSUE TITLE
also check code in /tests, /examples, etc.

### ISSUE THREAD

**Issue by mikeyhew** [rust-lang/rls-vscode#261]
This extension makes the experience of writing Rust code pretty nice. It would be even nicer if there was a way to enable it for code in the `/examples`, `/tests`, and `/benches` directories, at least for the files that are currently open. I looked through the list of settings and don't see anything that would enable checking that code.

Is there currently a way to turn on code checking for files in those directories? If not, could a setting be added that supported them? For my case, I'd like to do the equivalent of `cargo check --all-targets`, but I'd imagine other people would want a more fine-grained approach. Only checking tests, benches and examples that are open in the editor is probably a desired option.

**Comment by c410-f3r** [comment]
Related #232

**Comment by rocallahan** [comment]
Recent RLS build support a `rust.all_targets` option. If you're using such a build you can set `"rust.all_targets": true` in the settings.

**Comment by mooman219** [comment]
Related #281

**Comment by Xanewok** [comment]
Recently `all_targets` has been enabled by default and should be supported now.
