### ISSUE TITLE
Remove support for rustDocument/diagnostics{Begin,End} for 1.0 RLS release

### ISSUE THREAD

**Issue by Xanewok** [rust-lang/rls-vscode#264]
Since RLS is still in preview and didn't hit 1.0 yet, I think it's a good idea to remove the support for our previous _diagnostics*_ custom messages, before the 1.0 release, allowing for some transition period now. Especially since we moved to using more widely supported LSP extension messages.

@nrc @algesten what do you think about it?

**Comment by nrc** [comment]
Yes, for sure we should. I thought we could deprecate and then remove pretty quickly, just wait for the clients to update.

**Comment by algesten** [comment]
Agree! Out with the old, in with the new :P

**Comment by Xanewok** [comment]
Removed in the 0.6 version.
