### ISSUE TITLE
Rename silently fails

### ISSUE THREAD

**Issue by Phrohdoh** [rust-lang/rls-vscode#291]
```
$ rustc --version
rustc 1.25.0 (84203cac6 2018-03-25)

$ cargo --version
cargo 0.26.0 (41480f5cc 2018-02-26)

$ rustup --version
rustup 1.11.0 (e751ff9f8 2018-02-13)

$ rls --version
rls-preview 0.125.1-stable (cebf188 2018-03-19)

$ code --version
1.21.1
79b44aa704ce542d8ca4a3cc44cfca566e7720f1
x64

$ code --list-extensions --show-versions | grep rust
rust-lang.rust@0.4.1
```

When attempting to rename a symbol (the type doesn't seem to make a difference, item, variant, function name, etc.) the symbol *is not renamed* and there is *no output* in any of the output channels.

This is very frustrating as a user.

**Comment by nrc** [comment]
Do you have an example which does this? We deliberately do nothing in some cisrcumstances (e.g., field shorthand syntax which would be broken by the change), but in general it should succeed.

We should probably also explain what happened, if we do nothing.

**Comment by ridho9** [comment]
As for me, I'm trying to rename enum Value [here](https://github.com/ridho9/rlox/blob/ef89ecc5730b037438856bc1f674de71e6e0443b/src/ast/token.rs#L81).

**Comment by nrc** [comment]
I expect that it is the `#[derive(Clone)]` which is causing this to fail. The fix might be a bit long in coming since it requires some sophisticated knowledge of macros.

**Comment by Geobert** [comment]
Is there any workaround?

**Comment by glennpratt** [comment]
An error message saying this just doesn't work in some (many?) cases would at least save some confusion. No clue how feasible that is of course.

**Comment by whopper** [comment]
I had the same issue with renaming this simple function:
```
pub fn is_memory_available() -> Result<bool> {
...
```

```
> rustc --version
rustc 1.27.0 (3eda71b00 2018-06-19)

> cargo --version
cargo 1.27.0 (1e95190e5 2018-05-27)

> rustup --versionrustup 1.11.0 (e751ff9f8 2018-02-13)

=> rls --version
rls-preview 0.127.0-stable (d2ade31 2018-05-08)

Code: Version 1.25.0 (1.25.0)

Code: Rust (rls): 0.4.7
```

**Comment by ralfbiedert** [comment]
Another example where and how it fails for one of two neighboring parameters:

https://streamable.com/i6zgl

The file is from RLS. 

It is totally non-obvious why one of the two works and the other one does not.

**Comment by Xanewok** [comment]
RLS now uses LSP to warn why rename failed - https://github.com/rust-lang/rls-vscode/issues/223#issuecomment-480598958. This is still an RLS bug that needs to be solved there, however we now message the user so I'll close this issue for now (tracked elsewhere).
