### ISSUE TITLE
RLS fails to start, error running rustup

### ISSUE THREAD

**Issue by marmistrz** [rust-lang/rls-vscode#293]
I'm getting a warning:
```
RLS could not set RUST_SRC_PATH for Racer because it could not read the Rust sysroot.
```
later on: 
```
Unexpected error initialising RLS - error running rustup
```
in the `Rust Language Server` logs:
```
[Error - 1:38:05 PM] Starting client failed
Error: Error starting up rls.
	at /home/marcin/.vscode/extensions/rust-lang.rust-0.4.1/out/src/extension.js:127:19
	at Generator.throw (<anonymous>)
	at rejected (/home/marcin/.vscode/extensions/rust-lang.rust-0.4.1/out/src/extension.js:14:65)
	at <anonymous>
```

**Comment by marmistrz** [comment]
When trying to `rustup component add rust-src`, as advised by @Xanewok rustup complained that there is no default toolchain. 

After 
```
rustup install nightly
rustup default nightly
```
and installing rls via `rustup components` (as described in the rls readme) the problem was gone.

Nevertheless, a more helpful error message would be nice.

**Comment by marmistrz** [comment]
Unfortunately, I have encountered a very similar error after cleaning `~/.rustup` with `rm -rf ~/.rustup`. Unfortunately, I can't fix it anymore.

As previously, I tried to install the nightly toolchain. Due to #51699 I needed to specify it manually: (it looks like RLS VSCode won't work with the stable toolchain)
```
rustup install nightly-2018-06-18
rustup default nightly-2018-06-18
rustup component add rls-preview rust-analysis rust-src
```

The error message is exactly the same.

**Comment by nrc** [comment]
@marmistrz could you try again today please? Nightly on rustup has been broken for a few days but should now be fixed.

**Comment by robatipoor** [comment]
I'm getting same error in stable-x86_64-unknown-linux-gnu - rustc 1.33.0 (2aa4c46cf 2019-02-28) and nightly-x86_64-unknown-linux-gnu - rustc 1.35.0-nightly (f22dca0a1 2019-03-05)

**Comment by flxo** [comment]
@robatipoor Looks like the #517.

Adding `rust.channel` worked for me as well.

**Comment by jgilray** [comment]
The same thing that happened to @robatipoor also happened to me.  Thanks for the guidance on how to fix it.

For those (like me), who need a little more hand-holding on vscode, here is what I did to fix it, step-by-step:
1) Open vscode,
2) Menu: File -> Preferences -> Settings
3) Under "User Settings", click "Extensions", click "Rust configuration"
4) Near the top, under "Rust client: Channel" click "edit in settings.json"
5) Add the following line: "rust-client.channel": "stable"

So the file looks something like this:
{
    "window.zoomLevel": 0,
    "rust-client.channel": "stable"
}

6) Now save.  When you next open a workspace and edit a .rs file, RLS should work as expected.  Note that RLS only works in a workspace.

**Comment by tigerwill90** [comment]
> The same thing that happened to @robatipoor also happened to me. Thanks for the guidance on how to fix it.
> 
> For those (like me), who need a little more hand-holding on vscode, here is what I did to fix it, step-by-step:
> 
> 1. Open vscode,
> 2. Menu: File -> Preferences -> Settings
> 3. Under "User Settings", click "Extensions", click "Rust configuration"
> 4. Near the top, under "Rust client: Channel" click "edit in settings.json"
> 5. Add the following line: "rust-client.channel": "stable"
> 
> So the file looks something like this:
> {
> "window.zoomLevel": 0,
> "rust-client.channel": "stable"
> }
> 
> 1. Now save.  When you next open a workspace and edit a .rs file, RLS should work as expected.  Note that RLS only works in a workspace.

Thank's, that was the solution for me !

**Comment by Xanewok** [comment]
We now surface a lot more errors as to why RLS could not be started or installed, so I'll close this issue.
