### ISSUE TITLE
Version of `rls` being run

### ISSUE THREAD

**Issue by alexreg** [rust-lang/rls-vscode#297]
I am using I custom toolchain for a certain project I'm working on in VS Code, with a rustup override. It seems to be using the wrong version of `rls`, even though `rustup` knows where to find it. Is there any way I can check which version of `rls` is getting used?

**Comment by Xanewok** [comment]
I'm really sorry for a year-long delay, this repository hasn't received much love during that time. You could run VSCode with `RUST_LOG=rls`, navigate to the project and see the Output > Rust Language Server output pane. The first line should contain information about which RLS version is running currently.

**Comment by alexreg** [comment]
That's alright. Thanks for the answer.
