### ISSUE TITLE
Ability to show the complete definition of a function while typing

### ISSUE THREAD

**Issue by hifi** [rust-lang/rls-vscode#300]
Currently when you are writing a function call the IntelliSense/suggestion box is only shown for the function name. The argument list is hidden when you are writing the actual arguments.

Consider this snippet where `$` is the cursor:
```
fn do_something(foo: i32, bar: String, baz: f64) {
    // things
}

fn main() {
    do_something($);
}
```

I should be able to have a suggestion box visible under my cursor that shows the complete function definition with the argument types (`fn do_something(foo: i32, bar: String, baz: f64)`) while typing, preferably highlighting the current argument.

**Comment by Xanewok** [comment]
Implemented as part of #199.
