### ISSUE TITLE
Status indicator broken with latest VSCode

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rls-vscode#331]
Just updated to VSCode 1.23.1, and it seems like the status indicator at the bottom stops updating after a while. Not sure if it's related to the update.

> rls-preview 0.126.0-stable (5b79fcf 2018-04-07)

**Comment by Xanewok** [comment]
Can't repro this and have been using it for quite some time now; I'll close this for now but please reopen if that's still an issue!
