### ISSUE TITLE
No "Run test" lens when test #[should_panic]

### ISSUE THREAD

**Issue by zmwangx** [rust-lang/rls-vscode#432]
A screenshot should explain it:

<img width="506" alt="screen shot 2018-09-30 at 3 44 21 pm" src="https://user-images.githubusercontent.com/4149852/46261885-dc65df80-c4c7-11e8-92cc-b0f3505abde5.png">

The upper `#[test]` has the "Run test" lens, while the lower `#[test] #[should_panic]` does not. Would be nice to support the `#[should_panic]` case too.

CC @matklad who implemented this lens.

(rls-vscode v0.4.10)

**Comment by bspeice** [comment]
Can confirm that this is an issue. If you put the `#[test]` attribute below `#[should_panic]` it's detected correctly.

**Comment by andreevlex** [comment]
When add line between "#[test] " and " fn " does not work:
correct
![1](https://user-images.githubusercontent.com/20382553/54337933-76b67b80-4641-11e9-8d14-ec882b22d261.png)

not work
![2](https://user-images.githubusercontent.com/20382553/54337952-859d2e00-4641-11e9-9a62-dc7c503eb902.png)

**Comment by Xanewok** [comment]
This is due to RLS using a strict `#[test]\n\ *fn (name)` (pseudo)regex, which can't handle attributes in-between. This should be fixed upstream.

**Comment by CptFox** [comment]
This regex should cut it: `\#\[test\](\n|.)*^[^\/]*fn (\w+)`

**Comment by Gowee** [comment]
@zmwangx Now that the problem has been fixed by the above PR in upstream *rls*, this issue can now be closed?

**Comment by zmwangx** [comment]
Sure.
