### ISSUE TITLE
Sometimes there is a problem with the autocomplete code

### ISSUE THREAD

**Issue by Nify** [rust-lang/rls-vscode#433]
rustc -V
rustc 1.31.0-nightly (de3d640f5 2018-10-01)
os：windows 10（64）
 rustup toolchain list
nightly-x86_64-pc-windows-gnu (default)
Rust(rls) v0.4.10
***
Such code 
```Rust
let mut children=vec![];
```
Then spin up another thread,it autocomplete `thread::spawn...` will be like 
```Rust
children.push(thread::spawn(move || {
            println!("this is thread numer{}",i);
        });)// rustc will output error 
```
The last semicolon should be after the last closing parenthesis
```Rust
 children.push(thread::spawn(move || {
            println!("this is thread numer{}",i);
        }));//correct code
```

**Comment by Xanewok** [comment]
if I understand correctly this is the issue with `thread::spawn` snippet, which just copies the snippet code and as such is rather incomplete. To make it more versatile and work in expression positions, I believe the fix would be to put the cursor immediately after the expression and not automatically insert the semicolon at the end.
