### ISSUE TITLE
Unused import warning sometimes underlines wrong line

### ISSUE THREAD

**Issue by ablakey** [rust-lang/rls-vscode#440]
I found that the underline warning that I have an unused import can appear if I:

1. mis-order some imports
2. have an unused import
3. save the file
4. observe the order of imports automatically get fixed (because the file was saved)

![peek 2018-10-28 18-37](https://user-images.githubusercontent.com/9021944/47622890-dcfe8f80-dae0-11e8-9b22-c33b4d52b15a.gif)

VSCode: 1.28.2
rls-vscode: 0.4.10

**Comment by Xanewok** [comment]
Can't reproduce it with current nightly and VSCode 1.33.
