### ISSUE TITLE
RLS can't find rand crate

### ISSUE THREAD

**Issue by Itchy-Sand** [rust-lang/rls-vscode#442]
so I added the rand crate to my project as per the following:
extern crate rand;
use rand::Rng;

and now I'm getting 2 problems at the bottom status bar in VSCode.
1. can'f find crate for 'rand' can't find crate
2. miltiple matching crates for 'rand' note: candidates: 'rand'... and the path to the toolchains.

the code compiles without any problems and it's not affecting functionality, but I'm not sure where this is coming from and how severe this issue is.

**Comment by nrc** [comment]
Did you add it to Cargo.toml? The RLS watches Cargo.toml, so unless that changes it won't notice that a crate has been added.

**Comment by Itchy-Sand** [comment]
actually no I didn't, I try that. thanks

**Comment by Itchy-Sand** [comment]
> Did you add it to Cargo.toml? The RLS watches Cargo.toml, so unless that changes it won't notice that a crate has been added.

actually no I didn't, I'll try that and let you know.

**Comment by n0manarmy** [comment]
My issue with this was related to Visual Studio Code and that in the cargo file I had:
rand = "*"

I moved my Cargo.toml import to reflect rand = "0.6.5" and Visual Studio Code stopped complaining about the import. I know this for this particular issue but hopefully google will bring someone else to this answer and it'll help.
