### ISSUE TITLE
Code completion just compatible with "LF" line ending

### ISSUE THREAD

**Issue by Elementals** [rust-lang/rls-vscode#443]
As was originally mentioned [here](https://github.com/rust-lang-nursery/rls-vscode/issues/386#issuecomment-428216946), code completion is not compatible with "CRLF" line ending.
![bug code_completion](https://user-images.githubusercontent.com/29172351/47914685-7eb81f00-dedb-11e8-8869-19ed04ec18cc.png)
Here I use Amethyst (game engine) as an example, but for simple projects which just using a rand crate the bug will appear too.
I'm not sure this is caused by the `rls-vscode` or `RLS` or `Racer` though.

Also, Racer require nightly rust, why you haven't mention this in the VSCode page? (And this causes huge difference indeed, never get code completion worked in stable rust.)

**Comment by nrc** [comment]
> Also, Racer require nightly rust, why you haven't mention this in the VSCode page? (And this causes huge difference indeed, never get code completion worked in stable rust.)

It should work with any Rust if you're using the version installed by Rustup. Are you having problems with your own RLS build or with the Rustup one?

**Comment by Elementals** [comment]
I used **Rustup** to install the `stable rust`, with the extension installed properly but didn't run properly, and then I install `nightly rust` using **Rustup**, still got some problems (but slightly better than in stable). Finally I found out it was caused by line endings. So I switched back to see if this workaround applies to stable rust, but not.

So I installed both stable and nightly using Rustup, and using the extension from official (installed inside VS Code).

p.s. I'm using Windows.

**Comment by doxxx** [comment]
I'm experiencing this issue as well on Windows with rust 1.31 (final).

**Comment by jonathansty** [comment]
Experiencing this the the MSVC toolchain of `rustc 1.32.0-beta.6 (a01b0bf0f 2018-12-19)`. 

Changing the line ending to `LF` for the file fixes the completion only for that file. Although the completion shows completions that are located in files that still use `CRLF` endings.

**Comment by doxxx** [comment]
If I were to guess, I'd say that the extra character in CRLF is throwing off a file offset calculation somewhere.

**Comment by Xanewok** [comment]
This was fixed in https://github.com/racer-rust/racer/pull/1007 (18 days ago?), I believe the nightly rls should have the fix. Could you try the nightly version to see if it’s working there?

**Comment by doxxx** [comment]
Yeah, it's working with nightly rls.

**Comment by Elementals** [comment]
> This was fixed in [racer-rust/racer#1007](https://github.com/racer-rust/racer/pull/1007) (18 days ago?), I believe the nightly rls should have the fix. Could you try the nightly version to see if it’s working there?

Yes, now it works properly after I update rust to latest version, the stable rust also works properly now. Good fix!
But the OUTLINE seems broken? It always says "No symbols found in document ...".
