### ISSUE TITLE
No autocomplete with multiple files (shows only completions for root)

### ISSUE THREAD

**Issue by cfsamson** [rust-lang/rls-vscode#444]
**Problem**
RLS works as expected when I edit everything in one file, i.e. main.rs or lib.rs, but when I add a new file (submodule) RLS will not autocomplete correctly in the second file. It looks like RLS is searching the root for suggestions.

**Steps to reproduce**

1. Initialize a new project in an empty folder "cargo init --lib"
2. Bring File into scope "using std::fs::File"
3. Create a function and write "let file = File::" and completions work correctly
4. Declare a submodule "mod mymod;"
5. Create a new file "mymod.rs"
6. Repeat step 2 -3 in the new file and see the suggestion comes up, but it suggests "File" instead of File's methods.

**System and configuration**
- Operating system: Windows 10 Home
- VS Code version 1.28.2
- Rust toolchain:

> stable-x86_64-pc-windows-msvc (default) - rustc 1.30.0 (da5f414c2 2018-10-24)
- RLS plugin configured pretty much with default settings, only changes are:
_"rust-client.updateOnStartup":_ true,
_"rust.goto_def_racer_fallback":_ true,

**Additional information**
The best way to explain how this pans out is these two screenshots:

**In lib.rs**
![rls1](https://user-images.githubusercontent.com/8337848/48024518-284c1a00-e141-11e8-8c3b-059f96bc1d18.png)
**In mymod.rs**
![rls2](https://user-images.githubusercontent.com/8337848/48024532-3306af00-e141-11e8-9008-4349b32fd230.png)

**Comment by cfsamson** [comment]
Btw, I have tried: 

- moving my_modules.rs as the first pane, and restart RLS.
- Closing VS Code, only opening my_mod.rs and see if it works
- Switching to nightly to see if that has any effect
- Installing VS Code on another Win 10 machine and setting up Rust on that one, but same problem.

**Comment by cfsamson** [comment]
By coincidence I noticed that this issue seems to be related to #443.

In VS Code, go to settings and find the setting called "eol", on windows this defaults to CRLF "\r\n". If you change the setting to LF "\n", sugesstions pop up again in other files as expected. If you change this in an exisiting project already written with CRLF, the RLS plugin will work but seems to struggle (showing suggestions for wrong line etc on occations) but if you start a project with "eof" set to "\n" it seems to work.

**Comment by Xanewok** [comment]
Broken autocompletion due to LF/CRLF EOL has been merged in Racer for some time now, so this should be fixed.
