### ISSUE TITLE
No completion for "asdf".chars

### ISSUE THREAD

**Issue by arve0** [rust-lang/rls-vscode#445]
When typing `"asfd".ch`, one does not get `.chars()` as completion. I'm unsure if this is due to the plugin, or the Rust Language Server.

I do get other completions:

<img width="901" alt="image" src="https://user-images.githubusercontent.com/4810521/48138411-90674100-e2a4-11e8-9351-ab0426a9eed1.png">

And when hovering over `.chars`, I get a popup with signature and documentation:

<img width="689" alt="image" src="https://user-images.githubusercontent.com/4810521/48138470-ad9c0f80-e2a4-11e8-960d-789c3b8e7763.png">

Similar case with `"asdf".chars().for_each`, though no completions at all at `"asdf".chars().`.

**Comment by robertohuertasm** [comment]
It seems that this will work if you change to `nightly`. At least, the `chars` method. Not working for `for_each`, though.

**Comment by arve0** [comment]
Same here on 1.31, get completion for `.chars`, but not `.chars().for_each`.

I removed an old toolchain, and now have only stable installed:

```
$ rustup toolchain list
stable-x86_64-apple-darwin (default)
```

**Comment by Xanewok** [comment]
Both `"asdf".chars` and `"asdf".chars().for_each` work for me using the most recent RLS (and so the newest Racer, which powers the autocompletion), so I'm closing this. Please reopen if this still persists or ideally open a new issue against the RLS repository if autocompletion fails.
