### ISSUE TITLE
Unable to open 'iterator.rs': File not found

### ISSUE THREAD

**Issue by bluealert** [rust-lang/rls-vscode#451]
```
Unable to open 'iterator.rs': File not found (file:///Users/tao/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/src/libcore/iter/iterator.rs).
```

I want to go to the definition of a function defined in the standard library, but the path is wrong.

`rustlib/src/rust/`**src/src**`/libcore/iter/iterator.rs`

**Comment by jonasbb** [comment]
This is already being addressed at https://github.com/rust-dev-tools/rls-analysis/pull/158

**Comment by nrc** [comment]
Should be fixed on master now
