### ISSUE TITLE
RLS crashes building a path specified dependency

### ISSUE THREAD

**Issue by ncoish** [rust-lang/rls-vscode#455]
When I open VScode at the workspace root of a project I'm working on which has a dependent subcrate (specified in Cargo.toml as `my_crate = { path = "my_crate" }` ), while RLS is compiling my dependencies, once it gets to this crate, the icon indicating RLS activity just keeps spinning with "my_crate" listed after it. After about 10 seconds I get: "The Rust Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted".

If I open VScode in the "my_crate" crate root itself, RLS compiles everything perfectly fine, and I can use RLS properly. I have tried running with `RUST_LOG=info`, but nothing is ever printed to the debug console. Any ideas would be appreciated, as I'm really not sure why this only seems to apply to this project.

Let me know if I can provide any more information.

**Comment by Xanewok** [comment]
Hi, I'm using a following RLS wrapper that is useful when debugging: https://gist.github.com/Xanewok/fd87557d1b946ca4590da35bf41139ec (it should create a `~/rls-$DATA.log` file containing RLS stderr from a given run).

Could you try running the extension with the `"rust-client.rlsPath": "/home/<user>/rls_wrapper.sh"` (or wherever the script is, using the absolute path) setting and paste the log here?

**Comment by ncoish** [comment]
@Xanewok One important piece of information I forgot to provide is that I'm running on Windows, so that bash script doesn't seem like it's going to work (VSCode gives a warning "Could not start RLS"), I'll have to make an equivalent batch script

**Comment by ncoish** [comment]
After rebuilding the dependency again, RLS started working in my top-level crate. I haven't been able to reproduce the failure so unfortunately I won't be able to get to the root of what caused the issue. I'll close this issue for now and reopen if the issue occurs.
