### ISSUE TITLE
Format on save not triggering

### ISSUE THREAD

**Issue by rcuhljr** [rust-lang/rls-vscode#463]
After updating Format on save stopped working for me, and it always shows RLS as building in the spinner in the lower left. I'm on the nightly build of rust.

Just let me know what addition information would be helpful.

**Comment by rcuhljr** [comment]
This may be an issue with the nightly branch and rust fmt. I'll keep poking at it.

**Comment by rcuhljr** [comment]
Ok even after getting `cargo +nightly fmt` working on the command line again when I open up vscode the RLS building spinner starts up and never stops and I don't seem to be getting formatting or compile messages.

**Comment by nrc** [comment]
What project are you working on? Is there anything you did to get into the 'always spinning' state?

**Comment by rcuhljr** [comment]
I picked rust as a new language to learn while doing advent of code, the entire repo is pretty small if you want to test out what I'm seeing to see if you can reproduce it.
https://github.com/rcuhljr/aoc2018

I can't think of anything that triggered it, I applied the update and since then each time I open up the project fresh it just starts spinning.

**Comment by rcuhljr** [comment]
I tested on a different machine, same repository, same install (nightly), same behavior after restart.

**Comment by nrc** [comment]
What platform are you on? If you try `cargo check` do you see any error messages?

I couldn't repro: I cloned the repo and added it as a folder in a VSCode workspace. The RLS builds the repo fine, and format on save also works. Any idea what you might be doing differently?

**Comment by rcuhljr** [comment]
Windows 10, no errors on `cargo check` I've got it working now on a third machine without the error. So I'm not sure what's going on. I'm willing to close this for now and switch off the nightly where it's giving me troubles. If someone else experiences this we can try and find commonalities.

**Comment by rcuhljr** [comment]
One final note for anyone else experiencing this. Swapped to stable, didn't change anything. Noticed that in task manager even with VSCode closed I had ~5 copies of rls.exe running. Killing all of them didn't seem to fix the issue but a final reboot after killing them all and things are back to normal.

**Comment by ZacLiveEarth** [comment]
I am experiencing this issue when on nightly as well. If formatOnSave is enabled, after saving the RLS spinner spins forever with the message [building]. Unfortunately, I cannot switch to stable because I am depending on some features in nightly. Can we re-open this issue?
