### ISSUE TITLE
Panic with RLS 1.31.0 and latest vscode extension

### ISSUE THREAD

**Issue by olson-dan** [rust-lang/rls-vscode#468]
RLS is panicking on 1.31.0 with vscode extension v0.5.1 whenever opening a folder that uses cargo workspaces.  Opening any sub-folder works.  v0.5.2 looks like it was intended to address this based on the changelog, but I am still getting the issue under that version.

Since RLS and the VSCode extension were updated at around the same time, it's not clear which is causing the issue.  However it seems very-specific to vscode.  See this issue: https://github.com/rust-lang/rls/issues/1173

**Comment by olson-dan** [comment]
I downgraded to 0.5.0 using the instructions [here](https://tpodolak.com/blog/2017/04/09/downgrading-visual-studio-code-extension/) and it resolved the issue.

**Comment by mwrock** [comment]
I am seeing this same behavior with workspaces on v0.5.2.

**Comment by LaylConway** [comment]
Same behavior here, it's broken my workflow ever since 0.5.1

**Comment by crlf0710** [comment]
I did some basic debugging, and found that this is the data rls received: 
InitializeParams { process_id: Some(18348), root_path: Some("\\ThirdParty\\crlf0710\\xxx-rs"), root_uri: Some("file:///ThirdParty/crlf0710/xxx-rs"), ... }

I'm windows user, so this path is missing the drive part. I guess that's why rls panicked, though. I'm not sure which part of the code generates these paths, though.

**Comment by crlf0710** [comment]
After a little more debugging, I found that it's this code that causes this problem:
``` return Object.assign({}, cur_workspace, { uri: vscode_1.Uri.parse(current) }); ```
when current is: ```l:\ThirdParty\crlf0710\xxx-rs```
the result uri is:
```{$mid: 1, path: "\ThirdParty\crlf0710\xxx-rs", scheme: "l"}```
however what's expected is something like:
```{$mid: 1, external: "file:///l%3A/ThirdParty/crlf0710/xxx-rs", fsPath: "l:\ThirdParty\crlf0710\xxx-rs", path: "/l:/ThirdParty/crlf0710/xxx-rs", scheme: "file"}```

So, what's the correct way to generate a file scheme uri from filesystem path?

**Comment by Xanewok** [comment]
Is that still the case in the 0.6.1?

**Comment by olson-dan** [comment]
I'm on 0.6.1 now, and it appears to be working fine.
