### ISSUE TITLE
0.5.2 and 0.5.3 + RLS stable from Rust 1.31 does not start

### ISSUE THREAD

**Issue by Geobert** [rust-lang/rls-vscode#470]
I've uninstalled nightly toolchain, installed RLS from stable, started VS Code and got:
```
[Error - 6:00:56 PM] Starting client failed
Error: Error starting up rls.
	at ClientWorkspace.<anonymous> (C:\Users\Geob\.vscode\extensions\rust-lang.rust-0.5.2\out\src\extension.js:402:23)
	at Generator.throw (<anonymous>)
	at rejected (C:\Users\Geob\.vscode\extensions\rust-lang.rust-0.5.2\out\src\extension.js:14:65)
	at <anonymous>
```

![image](https://user-images.githubusercontent.com/72570/49689056-5c857280-fb13-11e8-9855-80a97bc5e734.png)

**Comment by Geobert** [comment]
Even with freshly out 0.5.3

**Comment by ashemedai** [comment]
For what it is worth: I have rust 1.31.0 installed along with 0.5.3 of the extension and RLS works for me without problems, can autocomplete and so on.

**Comment by Geobert** [comment]
Thanks for you insight, I'm stupid, I forgot a setting that use nightly channel…
