### ISSUE TITLE
Why has local Cargo.toml detection been reverted?

### ISSUE THREAD

**Issue by MightyAlex200** [rust-lang/rls-vscode#471]
Version 0.5.3 comes with only one change: to revert the changes made in the last update, which had made it possible to use the language server extension in files where `Cargo.toml` was not in the root of the directory. I'm don't see any issue on GitHub relating to this breaking anything, so I'm just here to ask why it was removed.

**Comment by nocduro** [comment]
The RLS would keep crashing on Windows when used with workspaces. See #468

**Comment by MightyAlex200** [comment]
I see, I guess I missed some things in the diff, it did more than revert 0.5.2. Thanks.
