### ISSUE TITLE
RLS panics when invoked from master rls-vscode

### ISSUE THREAD

**Issue by tchebb** [rust-lang/rls-vscode#477]
cb2206e1e8df ("Add missing `full_docs` and `show_hover_context` config keys") exposed a bug in RLS where it panics when `full_docs` is specified as `null`. I have submitted rust-lang/rls#1192 to fix the bug in RLS; however, it might be prudent to revert cb2206e1e8df or specify `false` instead of `null` for `full_docs` so as to not break users who don't update RLS.

Example panic:

    thread '<unnamed>' panicked at 'internal error: entered unreachable code', src/config.rs:111:33

**Comment by olix0r** [comment]
I'm seeing a similar panic using version 0.5.4:

```
thread '<unnamed>' panicked at 'internal error: entered unreachable code', src/tools/rls/src/config.rs:111:33
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1009:5
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1009:5
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1009:5
```

**Comment by tchebb** [comment]
This is weird; I'm not able to reproduce this issue now even though it should be present on my system.

Regardless, RLS doesn't seem to have released the fix on their end for this issue yet (although it is in master). As a temporary workaround, specify `rust.full_docs` in `settings.json` to be either `true` or `false` (`false` is supposed to be the default). The bug is that, when we pass `null` for that option to RLS, it fails to set the default internally and crashes, so explicitly specifying the setting should fix it.

**Comment by Xanewok** [comment]
That's weird, RLS stable should contain the fix from https://github.com/rust-lang/rls/pull/1192. Which RLS version are you using?

**Comment by tchebb** [comment]
@Xanewok ah, that would explain why I couldn't reproduce it. I didn't see my fix in the latest RLS release tag, but I must have been looking at the wrong thing.

**Comment by Xanewok** [comment]
Yeah, my bad - we stopped tracking git releases and just ride the trains with regular Rust releases. It might be worth doing that again.

@olix0r what is your `rls --version`?

**Comment by olix0r** [comment]
@Xanewok I was probably on a slightly older version -- since commenting I updated to the most recent I don't see the issue anymore.

**Comment by Xanewok** [comment]
Glad to hear that! I'll close this issue, then.
