### ISSUE TITLE
No auto-complete for nested vec with structs

### ISSUE THREAD

**Issue by davyzhang** [rust-lang/rls-vscode#489]
```rust
struct Test {
    vecs: Vec<Vec<Test>>,
}

pub fn main() {
    let t = Test { vecs: Vec::new() };
    let ta = &t.vecs[0][0].vec;
}

```

```
rustc --version
rustc 1.31.1 (b6c32da9b 2018-12-18)
rls --version
rls-preview 1.31.7 (da98b4d 2018-12-18)
extension version 0.5.3 from market
```
![image](https://user-images.githubusercontent.com/576863/51093767-cca5a900-17e1-11e9-8104-f53d4a31aca4.png)

**Comment by theIDinside** [comment]
Am I missing something here, but isn't this because the field isn't marked with pub?

**Comment by Xanewok** [comment]
cc @kngwyu

**Comment by kngwyu** [comment]
Thanks I'll try it

**Comment by Xanewok** [comment]
I understand that this Racer-specific and there is already a tracking issue there, so I'm closing this one.
