### ISSUE TITLE
Feature request: Need a way to specify environment variables for unit test

### ISSUE THREAD

**Issue by davyzhang** [rust-lang/rls-vscode#490]
env_log needs an environment var to print debug information. For every test, I need to re-init it, kinda cumbersome to use. It would be nice to specify some global environment variable for every test in this project/mod/workspace.

I can think of some use cases like data password, local workspace path, remote service URL etc.

**Comment by Xanewok** [comment]
See https://github.com/rust-lang/rls-vscode/issues/246#issuecomment-480602653 - it's possible to set individual variables for the cargo test task (and also override the arguments to specify different tests, if necessary)
