### ISSUE TITLE
Can I indicate a network path for RLS ?

### ISSUE THREAD

**Issue by magj2006** [rust-lang/rls-vscode#494]
Dear sir,
Can I indicate a network path for RLS ?

**Comment by Xanewok** [comment]
Technically, the LSP isn't limited to local filesystem but in practice not a lot of effort has been made to make it easy to work with remote servers. As I said, the main pain point is the filesystem and synchronizing files across client/server, see https://github.com/Microsoft/language-server-protocol/issues/528 for more information.

Right now it's not possible and it's not prioritized unless LSP itself is adapted.
