### ISSUE TITLE
Working on `no_std` crates with a custom target specification

### ISSUE THREAD

**Issue by joepie91** [rust-lang/rls-vscode#500]
When working on eg. an operating system project (such as Philipp Opperman's [follow-along blog series](https://os.phil-opp.com/)), you'll have to use a custom `x86_64-unknown-none` target specification alongside `no_std` to be able to develop and build for the correct target.

Unfortunately, this seems currently unworkable in combination with `rls-vscode`; any attempt at using RLS will result in a failure to build dependencies, marking Cargo.toml as failed and not providing any code intelligence nor error markings anywhere else.

Upon inspection of `rls`' error output (via the "log stderr to file" extension option), it turns out that the problem is the lack of an available `core` build for the target:

```
{"message":"can't find crate for `core`","code":{"code":"E0463","explanation":"\nA plugin/crate was declared but cannot be found. Erroneous code example: [... snipped ...]
```

This is a [fairly common problem](https://stackoverflow.com/a/28034968/1332715) for custom target triples, and normally this is solved by using a tool like Xargo or [`cargo-xbuild`](https://github.com/rust-osdev/cargo-xbuild) for builds. But of course `rls-vscode` is not aware of this, and therefore fails to build it.

I'm not sure how to solve this with RLS (or if it is indeed currently solvable at all!), but this currently prevents ergonomic OS development.

**Comment by Xanewok** [comment]
Thanks, that's indeed a void in terms of tooling support. We're aware of the problem but most likely will waiit for std-aware/xargo-integrated cargo to help with that and unfortunately it's not high on the priority list. This is tracked upstream at https://github.com/rust-lang/rls/issues/309 so I'll close this issue if you don't mind.
