### ISSUE TITLE
RLS Lint on Save?

### ISSUE THREAD

**Issue by mjohnson324** [rust-lang/rls-vscode#505]
Is there a way to configure rls-vscode to lint on save? Right now it lints once I've stopped typing momentarily and I find this very distracting.

**Comment by jens1o** [comment]
Yeah, there is, using these settings.

![screenshot](https://user-images.githubusercontent.com/11234139/52897279-0730a600-31d3-11e9-889a-cc9a3629501a.png)

**Comment by mjohnson324** [comment]
That didn't work. I see warnings and errors pop up in my code moments after typing something before I have a chance to finish what I'm writing. I don't want any warnings to appear in **Problems** until after I've saved my code.

Something like **"eslint.run": "onSave"** that lints JavaScript files only after saving, but with Rust code.

![screenshot from 2019-02-17 20-26-07](https://user-images.githubusercontent.com/22113104/52922849-50c3e280-32f2-11e9-821b-b77fff6346fe.png)

**Comment by Xanewok** [comment]
I believe the build on save configuration got you covered, implemented in
https://github.com/rust-lang/rls/pull/422

pon., 18 lut 2019 o 02:27 Michael W Johnson <notifications@github.com>
napisał(a):

**Comment by mjohnson324** [comment]
Thank you. I thought **build_on_save** meant saving the file would trigger a build, as in compiling the code.
