### ISSUE TITLE
Duplicated completion entries

### ISSUE THREAD

**Issue by rpeshkov** [rust-lang/rls-vscode#506]
I have duplicated entries in completion list. Duplications are not everywhere, but i.e., for `env::args().` all functions will be present 3 times.

Here's gif with demo:
![2019-02-18 22-56-35 2019-02-18 22_57_05](https://user-images.githubusercontent.com/701068/52978276-e2a21d00-33d0-11e9-93b7-f3e45e00f53a.gif)

VSCode: 1.31.1
Extension version: 0.5.3
Any other RLS or Rust completion extension is not installed.

**Comment by rpeshkov** [comment]
Ok, so it seems like the problem in RLS itself. What I understood from description - it uses racer for providing completions. Tried to invoke racer manually. Here's the result:

```
λ racer complete 3 16 src/main.rs | rg collect
MATCH collect,1476,7,/Users/rpeshkov/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/../libcore/iter/iterator.rs,Function,fn collect<B: FromIterator<Self::Item>>(self) -> B where Self: Sized
```

So, `collect` occurs only once in racer's result.

Also, launched LSP inspector from Microsoft to check what language server sends to VSCode and found there 3 occurrences of `collect` function and other functions as well. Log file:
[rust.log](https://github.com/rust-lang/rls-vscode/files/2877672/rust.log).

Didn't manage to setup debuggable `rls` environment. I'm noob in rust. Hope to have success tomorrow :)

**Comment by rpeshkov** [comment]
Ok, figured out the problem. Prize goes to racer. I've tested racer completion while I had 2.0 version. RLS is built against 2.1 version. When I checked what happens when I invoke `racer complete 3 16 src/main.rs` on racer 2.1 - it returns me duplicated entries. It happens because before deduplication of matches, matches are not sorted and `dedup_by` function removes only consecutive elements.

Made a fix for this behaviour in Racer and opened PR https://github.com/racer-rust/racer/pull/1021

**Comment by Xanewok** [comment]
Fixed in https://github.com/rust-lang/rls/pull/1402, should be available in the newest *nightly* toolchain in 1-2 days.

**Comment by Xanewok** [comment]
Closing this as fixed (remember that it's available since *1.35*)

**Comment by inancgumus** [comment]
I guess this problem continues.

```bash
racer complete 16 9 src/main.rs
PREFIX 289,289,
MATCH username,2,4,src/main.rs,StructField,String
MATCH email,3,4,src/main.rs,StructField,String
MATCH sign_in_count,4,4,src/main.rs,StructField,u64
MATCH active,5,4,src/main.rs,StructField,bool
END
```

However, in VS Code, it looks like this:

![rust](https://user-images.githubusercontent.com/621232/83519032-f600cb00-a4e3-11ea-800f-7b6ed1bb0709.gif)

Please let me know if you need any other debugging information.

**Comment by relief-melone** [comment]
at least I'm not the only one. Any updates on this?
