### ISSUE TITLE
occasional stale warnings

### ISSUE THREAD

**Issue by jrheard** [rust-lang/rls-vscode#508]
Hi!

Sometimes VS Code continues to show me warnings long after I've fixed them.

For instance, in https://www.evernote.com/shard/s11/client/snv?noteGuid=0fff5242-8b23-4860-962f-2c47def825c1&noteKey=04073f7de08acf9a&sn=https%3A%2F%2Fwww.evernote.com%2Fshard%2Fs11%2Fsh%2F0fff5242-8b23-4860-962f-2c47def825c1%2F04073f7de08acf9a&title=fourteen.rs%2B%25E2%2580%2594%2Badvent_2018 , `window` did indeed used to be an unused field on ElfCooks, but I deleted it some hours ago, and the warning persisted in VS Code across many changes to many files. Similarly, the "unreachable statement" warning in that screenshot did used to really exist, but was fixed hours before the screenshot was taken. `cargo c` gives me a clean bill of health, but VS Code doesn't agree.

This has been happening to me for about a week now, on several different files. I'm not sure what causes it.

Is this a known issue? Is there something I should do to fix it? Is there some way for me to give you diagnostic information to help understand this behavior?

Thanks!

**Comment by pocesar** [comment]
delete `target` folder and `Cargo.lock`, restart the editor, should be good to go

**Comment by jrheard** [comment]
that does indeed seem to have fixed it!
