### ISSUE TITLE
Unknown RLS configuration: `goto_def_racer_fallback` 

### ISSUE THREAD

**Issue by pocesar** [rust-lang/rls-vscode#510]
- Version: 1.32.0-insider (user setup)
- Commit: 2e4d4a6bb16a65303b460795fa4ac734f9aea43e
- Date: 2019-02-21T06:18:29.174Z
- Electron: 3.1.3
- Chrome: 66.0.3359.181
- Node.js: 10.2.0
- V8: 6.6.346.32
- OS: Windows_NT x64 10.0.17763

```
rustc --version
rustc 1.34.0-nightly (f66e4697a 2019-02-20)

rls --version
rls 1.34.0 (0d6f53e 2019-02-14)

cargo --version
cargo 1.34.0-nightly (865cb7010 2019-02-10)
```

Editor is displaying a warning  today in the  "bell" at bottom right:

```
Unknown RLS configuration: `goto_def_racer_fallback
```

![image](https://user-images.githubusercontent.com/461084/53154287-33647200-3599-11e9-9326-f6393d694d7d.png)

**Comment by dvic** [comment]
I've also hit this, it's because https://github.com/rust-lang/rls/pull/1152 got merged. It was on Jan 8 but RLS builds were broken on nightly lately, so that's why we are seeing this only now.

**Comment by inikulin** [comment]
Still seeing this issue with `rls-vscode v0.5.4` and stable toolchain `v1.33.0`

**Comment by Xanewok** [comment]
Make sure you don't have it explicitly set in the settings.json, this shouldn't pop up now in general

**Comment by inikulin** [comment]
@Xanewok turned out it was the case, thanks
