### ISSUE TITLE
unable to start program

### ISSUE THREAD

**Issue by shehzadaliqadri** [rust-lang/rls-vscode#524]
Issue Type: <b>Bug</b>

While i have started vs code, it shows error starting up rls

Extension version: 0.5.3
VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:46:10.898Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz (4 x 1014)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|3.73GB (0.12GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by angusgraham** [comment]
Try with 0.5.4

**Comment by Xanewok** [comment]
Like @angusgraham said, this should be fixed with 0.5.4. Please download the newest version and try again (please do reopen if you still have the issue then).
