### ISSUE TITLE
rls ignores used integer whose value was updated

### ISSUE THREAD

**Issue by sntdevco** [rust-lang/rls-vscode#526]
Try typing this code into vscode with rls-vscode:
```
fn main() {
    let mut x: i16 = 5;
    x = 4; let name = String::from("Rustacean");
    println!("Hello there, I'm {} and I'm {} years old", name, x);
}
```
`x` is highlighted as unused in line 2, where it is declared and initialized. Now **I'm not sure** whether this is an issue with rls or with rls-vscode, but surely it's an error.

Environment:
**Operating System:** Ubuntu 18.04.2  LTS
**Rust Version**: rustc->1.32.0 and rls->1.31.6

**Comment by sfackler** [comment]
It's not an issue with rls or rls-vscode. The value `5` is never used. The compiler is telling you that it's unneeded:

```rust
fn main() {
    let mut x: i16;
    x = 4; let name = String::from("Rustacean");
    println!("Hello there, I'm {} and I'm {} years old", name, x);
}
```

**Comment by sntdevco** [comment]
> It's not an issue with rls or rls-vscode. The value `5` is never used. The compiler is telling you that it's unneeded:
> 
> ```rust
> fn main() {
>     let mut x: i16;
>     x = 4; let name = String::from("Rustacean");
>     println!("Hello there, I'm {} and I'm {} years old", name, x);
> }
> ```

Oh right, closing this (never knew rust was so smart!)
