### ISSUE TITLE
Issue installing RLS 0.5.4 on MacOS

### ISSUE THREAD

**Issue by greg5678** [rust-lang/rls-vscode#529]
I updated VSCode to 1.32.1 and then updated RLS to 0.5.4 but I still keep getting `RLS not installed. Install?`.

**Comment by tchebb** [comment]
What are your `rust-client` settings in `settings.json`? This sounds like it could be a side-effect of my change in #476, but the specific error you're getting doesn't make much sense to me.

Also, are there any messages in the console (Help → Toggle Developer Tools) from rls-vscode?

**Comment by greg5678** [comment]
Thanks for your help. I got it working and forgot to close the issue.
