### ISSUE TITLE
Disable RLS on workspace basis

### ISSUE THREAD

**Issue by alexreg** [rust-lang/rls-vscode#531]
Is there any way to disable RLS on a per-workspace basis? If not, I would like to request this feature. It is particularly useful when dealing with huge projects like rustc, where I don't want/need the RLS to run in the background and eat up CPU and memory.

**Comment by Xanewok** [comment]
I think you can disable the extension for the opened workspace in the extension view - click the small arrow near the "Disable" button and select "Disable (Workspace)".

**Comment by alexreg** [comment]
Thanks. That does the job.

**Comment by Xanewok** [comment]
Glad to hear that! If you don't mind, I'll close the issue then.
