### ISSUE TITLE
RLS intellisense not showing all methods

### ISSUE THREAD

**Issue by Acidic9** [rust-lang/rls-vscode#537]
I'm using a crate called `nannou` https://crates.io/crates/nannou

I am attempting to draw a line using `draw.line().start(...).end(...)`, but RLS does not show that `.start` or `.end` exist after `draw.line()`.

**RLS not showing method `.start`**
![SS1](https://i.imgur.com/0Z6CkRY.png)

**RLS able to find it when I manually type the method**
![SS2](https://i.imgur.com/2YCr1Gk.png)

---

In short: RLS is not displaying all possible methods and in many situations I am required to manually write the method name before RLS is able to detect the method and arguments.

---

Tested on both `stable-x86_64-pc-windows-msvc` and `nightly-x86_64-pc-windows-msvc`.

```
Default host: x86_64-pc-windows-msvc

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.33.0 (2aa4c46cf 2019-02-28)
```

**Comment by pocesar** [comment]
same thing with nightly

**Comment by dontpanic92** [comment]
It looks like stable-x86_64-pc-windows-gnu has the issue as well here

**Comment by Xanewok** [comment]
That's the issue with *compiler-backed completion*. Currently we use syntactical completion using Racer but it may miss some of the valid functions that Racer can't find itself. That's tracked upstream at https://github.com/rust-lang/rls/issues/6 so I'll close this issue.
