### ISSUE TITLE
AtomicUsize doesn't appear on std::sync::atomic::|

### ISSUE THREAD

**Issue by pocesar** [rust-lang/rls-vscode#548]
while after typing the whole struct, the tooltip appears:
![image](https://user-images.githubusercontent.com/461084/55056408-cedb7d80-5044-11e9-9e31-f93d27e1f0a1.png)

when typing `std::sync::atomic::` only shows:
![image](https://user-images.githubusercontent.com/461084/55056452-eb77b580-5044-11e9-9af9-982d4980c48f.png)

the reason I think is because it's inside a macro:
![image](https://user-images.githubusercontent.com/461084/55056515-12ce8280-5045-11e9-9252-4efa51e72874.png)

but when Ctrl + Clicking the "AtomicUsize" part, it goes to the declaration properly (as shown by the carret laying right there near AtomicUsize)

**Comment by Xanewok** [comment]
Unfortunately analysis for the macro-generated identifiers is a known issue in the RLS and does not work fully. This is an RLS bug itself and is tracked in several issues there, so I'll close this one.
