### ISSUE TITLE
Error when clicking problem in Problems Pane/List

### ISSUE THREAD

**Issue by miXwui** [rust-lang/rls-vscode#550]
Hi @yisonPylkita @Xanewok 
I believe this ties to #488  
#280 and #151 may be related as well  

I ran across this error on Windows 10/WSL/VSCode, happens when I click on a problem in the Problems pane. It should jump to the respective line in the file, but instead this error occurs:
![image](https://user-images.githubusercontent.com/4538842/55122682-c2e7ce00-50cd-11e9-9260-59287766ac53.png)

I did some debugging/poked around the code a bit, and realized that the issue occurs if there's a space in the path. If I move the project folder to say C:/guessing_game, all is well. But since my Windows user account includes my first and last name with a space in between, the path is ".../Users/**FirstName LastName**/..." which ends up being converted into ".../Users/**FirstName%20LastName**/...".

I found that if I simply replaced the "%20" in wslPath in protocol2Code with a regular space ' ' then the issue was resolved. I'm not sure if this is the best way to fix or what else it could affect:

```js
protocol2Code: (wslPath: string) => {
  if (wslPath.startsWith('file://')) {
    wslPath = wslPath.substr('file://'.length);
    // replace %20 with ' '
    wslPath = wslPath.replace('%20', ' ');
  }
```

**How to reproduce:**
Create a project in a location where the path has a space in it. Write code that will produce a problem in the VSCode Problems pane, and then click that specific problem.

**EDIT:**
These are the VSCode settings I'm using fyi, Rust is only installed in WSL Ubuntu 18.04.2 LTS and not on Windows.  
```json
"rust-client.useWSL": true,
"rust-client.rustupPath": "~/.cargo/bin/rustup",

**Comment by yisonPylkita** [comment]
Thanks @miXwui for filling this bug report.

I created #553 with a fix for this bug. Instead of `wslPath.replace('%20', ' ')` I used `wslPath.split('%20').join(' ')` to replace all `%20` s

**Comment by miXwui** [comment]
Oops, I forgot to use regex `wslPath.replace(/%20/g, ' ')` but that'll work too, thanks @yisonPylkita!
