### ISSUE TITLE
Can't run one test by clicking "Run test"

### ISSUE THREAD

**Issue by Geobert** [rust-lang/rls-vscode#559]
Using VSCode 1.32.3 and rls-vscode 0.6.0 and rust stable 1.33, when I click on "Run test" I have 2 notifications: 
![image](https://user-images.githubusercontent.com/72570/55515761-4328a900-5663-11e9-9e52-27d2407914af.png)

**Comment by Xanewok** [comment]
@Geobert could you try with the 0.6.1 version as well? Some task/command-related logic was tweaked and hopefully this works now (tested Run test myself on 0.6.1 but that may differ across the projects)

**Comment by Geobert** [comment]
It is solved in 0.6.1! Thank you very very much!
