### ISSUE TITLE
function name duplicated in tooltip

### ISSUE THREAD

**Issue by samuela** [rust-lang/rls-vscode#566]
![Screen Shot 2019-04-09 at 3 09 56 PM](https://user-images.githubusercontent.com/226872/55838564-bb66f280-5ad9-11e9-80c7-d6fb266146bf.png)

I'm on vscode Version 1.34.0-insider (1.34.0-insider) 56f1b4795fed05677eb82a21dac4fc1ab62d747b with extension version 0.6.1, and cargo 1.33.0 (f099fe94b 2019-02-12).

**Comment by samuela** [comment]
This happens immediately after I type `(`, and occurs regardless of whether the function is `pub fn` or just `fn`.

**Comment by Xanewok** [comment]
I believe this is caused by #552. What may be happening is that you're getting 'suggestion' for a function you're already definining, so it may be duplicating use and definition site in the tooltip as they're the same?
@radu-matei do you know offhand what may be causing this?

**Comment by radu-matei** [comment]
Ugh, yeah, this is an interesting case.. So how the tooltip works is uses the trigger characters `(` and `,` for the signature help and it checks whether the symbol right before `(` is a function definition, by making a request to RLS. If it is, it displays the tooltip.

The fix should be fairly straightforward -- if the function definition points to the same line as the cursor, don't show the tooltip.

Thanks for catching this, when I have a free cycle, I'll update this. If anyone gets to it before I have the time, here's where the check should take place - https://github.com/rust-lang/rls-vscode/blob/master/src/providers/signatureHelpProvider.ts#L12, for both trigger characters.
