### ISSUE TITLE
RLS panicked while building

### ISSUE THREAD

**Issue by HoOngEe** [rust-lang/rls-vscode#569]
RLS cannot complete building. I tried reset all the environments.
1. Cargo clean on my project.
2. Uninstall rust-rls extension from my VScode.
3. Remove `~/.config/Code` ,`~/.vscode` folder and re-installed VScode.
4. Re-install rust rls.

But still rust-rls could not complete its job to support extension functionality.
I turned on `rust-client.logToFile: true` and got the log file like below.

```
thread '<unnamed>' panicked at 'internal error: entered unreachable code', src/tools/rls/src/config.rs:111:33
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1009:5
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1009:5
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1009:5
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1009:5
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1009:5
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1009:5
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1009:5
thread 'request-worker-3' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1009:5
```
I don't know the cause of this problem.

**Comment by Xanewok** [comment]
@HoOngEe could you link to a project you're trying to open or is it closed-source? It seems you're hitting the assertion at https://github.com/rust-lang/rls/blob/49efc0694e0dd551b3f06d354bbc66a206f73a0c/rls/src/config.rs#L101. Could you tell me what is the output of `rls --version` and what are the `rust.*` settings in your settings.json in VSCode?

**Comment by HoOngEe** [comment]
@Xanewok I tried to open this open source projet https://github.com/CodeChain-io/codechain.

rls-version is 
```
~ rls --version
rls-preview 1.33.0 (9f3c906 2019-01-20)
```
and in settings.json
```
{
    "rust-client.logToFile": true,
    "rust.wait_to_build": 15000,
}
```

Thank you for the reply.

**Comment by HoOngEe** [comment]
RLS seems to be stabilized.
