### ISSUE TITLE
rustup command not found using WSL

### ISSUE THREAD

**Issue by chbdetta** [rust-lang/rls-vscode#570]
output in vscode
```
[Error - 6:14:11 PM] Starting client failed
Error: Command failed: wsl rustup toolchain list
/bin/bash: rustup: command not found

	at ChildProcess.exithandler (child_process.js:303:12)
	at ChildProcess.emit (events.js:182:13)
	at maybeClose (internal/child_process.js:961:16)
	at Socket.ChildProcess.spawn.stream.socket.on (internal/child_process.js:380:11)
	at Socket.emit (events.js:182:13)
	at Pipe.Socket._destroy._handle.close [as _onclose] (net.js:596:12)
```
`wsl rustup` ends up with a command not found error, it seems wsl won't load `~/.profile` using the aforementioned command.
However, `wsl bash -ic "rustup"` works if rust path is set in `.bashrc`.

The wsl current behavior is confirmed by another user here:
https://www.reddit.com/r/bashonubuntuonwindows/comments/9tsrym/default_shell_is_zsh_running_wsl_some_command/

and by a wsl member:
https://github.com/Microsoft/WSL/issues/2816#issuecomment-404945987

It seems `.profile` is always ignored and in order for wsl to parse `.zhsrc` / `.bashrc` you need commands like `wsl bash -ic rustup`.

**Comment by labooner** [comment]
I added the following to my settings.json and it fixed it.

"rust-client.rustupPath": "/home/me/.cargo/bin/rustup"

**Comment by TheDan64** [comment]
I'm getting a similar error:
```
> Executing task: wsl /home/dkolsoi/.cargo/bin/rustup component add rust-analysis --toolchain nightly-2019-04-12-x86_64-unknown-linux-gnu <

/bin/bash: wsl: command not found
```

**Comment by Xanewok** [comment]
We deprecated the WSL support in-extension, please try out the [Remote - WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) extension, instead (should fix all the path-related issues)
