### ISSUE TITLE
Unknown RLS configuration: `mode` ,`rustup`

### ISSUE THREAD

**Issue by japert** [rust-lang/rls-vscode#572]
## Observed behavior: 

Popup of "Unknown RLS configuration: `mode` ,`rustup`"
<img width="469" alt="Screen Shot 2019-04-12 at 8 53 20 AM" src="https://user-images.githubusercontent.com/31267991/56050643-483fc500-5d01-11e9-87c1-b530f59f4203.png">

Build indicator keeps spinning:
<img width="103" alt="Screen Shot 2019-04-12 at 8 53 29 AM" src="https://user-images.githubusercontent.com/31267991/56050638-45dd6b00-5d01-11e9-95b0-95c542d3c881.png">

[vscode.log](https://github.com/rust-lang/rls-vscode/files/3074091/vscode.log)

## Steps to reproduce
* open non-empty rust project in vs code with rls-vscode installed.

## Environment
* VS Code Version 1.33.1 (1.33.1)
* macOS 10.14.4 (18E226)
* rustc
  * stable-x86_64-apple-darwin (default)
  * rustc 1.34.0 (91856ed52 2019-04-10)
```
$ rustup component list --toolchain stable --installed
cargo-x86_64-apple-darwin
rls-x86_64-apple-darwin
rust-analysis-x86_64-apple-darwin
rust-docs-x86_64-apple-darwin
rust-src
rust-std-x86_64-apple-darwin
rustc-x86_64-apple-darwin
```

## Expected behavior: 
* rls-vscode extension shows no error
* rls-vscode finishes build

**Comment by dusty-phillips** [comment]
I had this as well and had to remove "rust.mode": "legacy" from my user settings. It appears they've disabled legacy mode. I can't remember why I turned it on in the first place, so that's all right.

**Comment by Xanewok** [comment]
I believe these options are for another extension - https://github.com/editor-rs/vscode-rust. I wouldn't recommend running both as they may spawn two instances of RLS or do overwrite each other tasks or similar. I believe that extension is quasi-deprecated at this point and this should be used instead, so in this case it's safe to remove `rust.mode` and `rust.rustup` entries from settings.json.

**Comment by japert** [comment]
You are right I had these orphan settings my user settings!
However the build indicator keeps spinning.
Might be related to https://github.com/rust-lang/rls-vscode/issues/492

**Comment by w614561012** [comment]
you need to delete the rust.mode and rust.rustup in the setting.json
