### ISSUE TITLE
Tasks do not work if terminal is WSL

### ISSUE THREAD

**Issue by kobenauf** [rust-lang/rls-vscode#575]
If the default VSC terminal is set to use WSL, cargo commands in tasks fail.  There is a config setting for rustupPath.  Cargo tasks should probably also use a cargoPath command.

Here are my current settings:
```
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\wsl.exe",
"rust-client.useWSL": true,
"rust-client.revealOutputChannelOn": "info",
"rust-client.rustupPath": "~/.cargo/bin/rustup",
```
Ideally I'd also set:
```
"rust-client.cargoPath": "~/.cargo/bin/cargo"
```

**Comment by AaronFriel** [comment]
This also fails if:

```
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\wsl.exe",
"rust-client.useWSL": false,
```

It looks like RLS assumes the integrated shell for running tasks in will be Windows-like, so setting the integrated shell to WSL breaks the "set up RLS" feature.

**Comment by Xanewok** [comment]
We deprecated the WSL support in-extension, please try out the [Remote - WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) extension, instead.
