### ISSUE TITLE
Error start RLS in version 0.6.1 with message "Rustup not available"

### ISSUE THREAD

**Issue by andreevlex** [rust-lang/rls-vscode#577]
Not started RLS with update rustup

message:
```log 
[Error - 15:01:20] Starting client failed
Error: spawn rustup ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
	at onErrorNT (internal/child_process.js:406:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
```
and plus this:
```
Rustup not available. Install from https://www.rustup.rs/
```

Before update rustup error message was same.

rls-vscode version = `0.6.1.`
rustup version = `rustup 1.17.0 (069c88ed6 2019-03-05)`
vscode vesion = `1.33.1`
rustc version = `rustc 1.34.0 (91856ed52 2019-04-10)`
os:
```
Distributor ID:	LinuxMint
Description:	Linux Mint 19.1 Tessa
Release:	19.1
Codename:	tessa
```

**Comment by jhzn** [comment]
Experiencing the same. Also running Linux Mint 19.1.

**Comment by andreevlex** [comment]
check in this os

```log
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

normal working.

**Comment by andreevlex** [comment]
@jhzn you try uninstall/install vscode extension?

**Comment by ricvelozo** [comment]
I'm using Fedora 29, VS Code from Flathub and Rust from official website. Reinstalling the extension did not resolve the issue.

**Comment by mike-engel** [comment]
Checking in with the following. Running VSCode from the icon and from the command line produces the same error.

```
VSCode: 1.33.1
rls-vscode: 0.6.1
macOS: 10.14.4
rustup: rustup 1.18.0 (8603e2c56 2019-04-22)
rustc: 1.31.1 (b6c32da9b 2018-12-18)
```

**Comment by andreevlex** [comment]
@Xanewok How you debugging this extension?
I am want try debugging on my machine.

**Comment by ameyat2812** [comment]
I was experiencing the same issue. Adding the following to my plugin settings fixed it

> "rust-client.rlsPath": "path_to_rls"

**Comment by jhzn** [comment]
I tried debugging this some. Sharing what I've found.
This fixes everything.
```json
"rust-client.rustupPath": "/home/XXX/.cargo/bin/rustup",
```
This seems to be an issue with the path.
``` 
echo $PATH
``` 
contains ~/.cargo/bin:
so I can run rustup --version fine in a shell.
However running the code below returns an error, the same error I got when debugging the extension.
```javascript
const { execFile } = require('child_process');
const child = execFile('rustup', ['--version'], (error, stdout, stderr) => {
  if (error) {
    throw error;
  }
  console.log(stdout);
});
/*
throws error:

Error: spawn rustup ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
*/
```
Which is the same way rustup is invoked in the extension [here](https://github.com/rust-lang/rls-vscode/blob/69107f6f8e2bc00c14657dae02ffcdec90bed877/src/utils/child_process.ts#L6)

**Comment by apshoemaker** [comment]
I can confirm that the above works for me - setting the proper path to rustup solved my issues.

System details:
VSCode: 1.33.1
rls-vscode: 0.6.1
Windows 10 Professional v17134.753

**Comment by andreevlex** [comment]
my command
```bash
echo $PATH
```

print this:

```log
/home/***/.cargo/bin:
```

Not work.

**Comment by WNemencha** [comment]
Ran into this issue too. I had `rustup` installed so the fix was just to restart VSCode because it was open before I installed rustup. Seems like a stupid error :')

**Comment by andreevlex** [comment]
My GNOME termimal read config file
`.bashrc`

```bash
# change PATH for support Rust.
export PATH="$HOME/.cargo/bin:$PATH"
```
command:

```
rustup --version
```
bash - work
vscode extension - not work

Added 
```bash
export PATH="$HOME/.cargo/bin:$PATH"
```
in `.bash_profile` and drop from `.bashrc`

rerun command:

```
rustup --version
```

bash - not work
vscode extension - *work*

Conclusion
VSCode extension need change `.bash_profile`.

**Comment by fredrikaverpil** [comment]
I had `export PATH="$PATH:~/.cargo/bin"` in my path. Changed it to `export PATH="$PATH:$HOME/.cargo/bin"` and now it works.

**Comment by andreevlex** [comment]
This not bug extension.
Bug:
1. VsCode
2. Rustup.

**Comment by ymgyt** [comment]
I've fixed same issue by adding the following settings to `setting.js`

```
// "~/.cargo/bin/rustup" does not work
"rust-client.rustupPath": "/absolute/path/to/.cargo/bin/rustup",
```

**Comment by hanzckernel** [comment]
Having the same problem on MacOS Sierra. Running fine on bash `rustup -V` but installing RLS did not work. Add

`"rust-client.rustupPath": "/Users/XXX/.cargo/bin/rustup",`

solves the problem.

**Comment by JacksonBailey** [comment]
> Ran into this issue too. I had `rustup` installed so the fix was just to restart VSCode because it was open before I installed rustup. Seems like a stupid error :')

Also, if you're on Mac, be sure you actually close the program and not just the windows. If you see the little dot beneath VS Code on the dock then it is still running. :)

**Comment by sffc** [comment]
Steps to fix:

1. Shift-Control-P to open the command palette
2. Type "User Settings" and hit enter
3. Go to Extensions -> Rust
4. Scroll down to "Rustup Path"
5. Put your absolute path to rustup in the text box
6. Reload the window: Shift-Control-P, type "Reload Window", and hit enter

**Comment by steelx** [comment]
Uninstalled Rust extension.
And installing Rust-analyzer fixed the issue for me.

**Comment by S-Mann** [comment]
Do a `rustup update` if you don't use `rustup` to manage your versions of `rust` packages and rust as well, I would suggest you to do so.

After `rust` is updated, make sure you install `rust-analysis` and few other packages that the vscode `rls` plugin uses.

To see your current components.

```bash
$ rustup component list | grep installed
```

Installing these packages should fix your issue. I agree this isn't the plugin's fault.
```bash
$ rustup component add rust-src rust-analysis
```
