### ISSUE TITLE
Logging structures refactoring

### ISSUE THREAD

**Issue by CodeSandwich** [rust-lang/rls-vscode#593]
# Context
Currently the logging infrastructure is based on passing around `Logger` objects. Some of them contain some context information, others not.

# Problem
It's extremely hard to track, what context information is outputted when using particular `Logger`.

Also `Logger` does not have any means of changing existing information. For example when `Logger` with `task: network` is derived and somebody tries to overwrite it with `task: server`, the child logger ends up with both of them causing mayhem in output.

# Solution
Create a group of structures of which every could be used instead of `Logger`.

Logging is performed using macros. Macros are duck-typed, so as long as logging structures have the same API as `Logger` (`log` method), they can be used as replacement.

The logging structures will have methods for explicit conversions between some of them. For example `NetworkLogger` -> `ServerLogger`. This will make altering their behavior in different contexts possible and easy to track.

**Comment by Xanewok** [comment]
I'm not exactly sure I follow. Do you mean [`env_logger::Logger`](https://docs.rs/env_logger/0.6.1/env_logger/struct.Logger.html)? I understand that this does not apply to the VSCode extension nor RLS code itself but rather to the code analyzed.

Which scenarios are you talking about and what do you exactly propose here?

**Comment by CodeSandwich** [comment]
I don't know how, but I've created an issue on a wrong project, sorry about that D:
