### ISSUE TITLE
Formatting wrongly removes use statements (destructive formatting)

### ISSUE THREAD

**Issue by leo-lb** [rust-lang/rls-vscode#603]
VSCodium `1.35.1`
Rust `1.35.0`
rls-vscode `0.6.1`

---

The issue happens when formatting this project at this particular commit;

https://gitlab.com/schmilblick/violetear/web-client/commit/5052df6d39463da505737d8be21d63ca975331f9

Few use statements get wrongly stripped in `src/main.rs`

**Comment by CryZe** [comment]
I‘m really confused why so few people run into this. This happens with pretty much every new use statement on stable and apparently beta and nightly too with RLS. It is a huge dealbreaker and very few people seem to complain about it. Is no one using RLS anymore or what?

**Comment by leo-lb** [comment]
https://github.com/rust-lang/rls-vscode/issues/576 contains quite a lot of affected users, but again, not everyone uses VSCode with RLS. It was working fine for a while, it only started doing this with some really specific code.

**Comment by feuerste** [comment]
As does #595 ... Seems like it is related to 1.35

**Comment by viktorku** [comment]
Duplicate of #576

**Comment by AlisCode** [comment]
I can reproduce and confirm that it seems to be related to VSCode 1.35. Very annoying indeed.

**Comment by CryZe** [comment]
This has nothing to do with VSCode 1.35. This happened like 2 months ago or so too. It roughly started with the release of Rust 1.35.

**Comment by Xanewok** [comment]
This made its way to Rust 1.35 but the fix is in beta now and so this should land in stable Rust 1.36 release.

**Comment by CryZe** [comment]
Wait, there's a fix? Can you link that?

**Comment by Xanewok** [comment]
@CryZe https://github.com/rust-lang/rls/pull/1455

**Comment by CryZe** [comment]
Nice, I just tried Beta and it indeed seems to be fixed. Thanks so much :D

**Comment by AlisCode** [comment]
Weird. In my case it really started happening with the latest VSCode but I guess it was just a coincidence of me updating everything at once. 
Glad to see there's a fix :)

**Comment by Xanewok** [comment]
Beta will be released in a week and so I'll close this issue if you don't mind. Thanks for reporting this! I'll pin https://github.com/rust-lang/rls-vscode/issues/576 to increase visibility of this issue and hopefully to reduce duplicate issues.
