### ISSUE TITLE
Unknown RLS configuration.

### ISSUE THREAD

**Issue by Tormenator1** [rust-lang/rls-vscode#608]
When I open a .rs file in VScode a alert pops up that says 

> Unknown RLS configuration: `mode` ,`rls` ,`rust_lang_src_path` ,`rustup` 

I am currently using the nightly toolchain.
How can I fix this?

**Comment by Xanewok** [comment]
Check if you have defined `"rust.XYZ"` settings (<key>Ctrl</key> + <key>,</key>) where XYZ is in `mode`, `rls` and the rest from the above.

It's possible that you set it for https://github.com/editor-rs/vscode-rust which is a different extension.

**Comment by Tormenator1** [comment]
I have not defined my `"rust.XYZ"` settings. How would I set it up for this extension?

**Comment by Xanewok** [comment]
I'd say the default settings are pretty good, you can consult https://github.com/rust-lang/rls-vscode/blob/8d870000cbf959457dbcf1f9e20e670bd6f798df/package.json#L146-L397
to see  which options are available.

Can you link your VSCode settings (found via Ctrl + , and clicking the `{}` (Open Settings (JSON)) in the top-right corner) here?

**Comment by Tormenator1** [comment]
[Here](https://gist.github.com/Tormenator1/dc7659c23f5c22237b73c3bcb0fe66fb) you go.

**Comment by Xanewok** [comment]
As you can see, these:
```
    "rust.rustLangSrcPath": "C:\\Users\\Kestor Brown\\.rustup",
    "rust.rls": {
        "executable": "rustup",
        "args": [
            "run",
            "nightly",
            "rls"
        ],
        "env": {
            "RUST_LOG": "rls=debug"
        }
    },
    "rust.rustup": {
        "toolchain": "nightly-x86_64-pc-windows-msvc"
    },
"rust.mode": "rls",
```
are set but all the `"rust.*"` are passed to the RLS which does not understand them (look up the linked supported settings, these are not on the list).

I personally use these:
```
"rust-client.channel": "nightly", // Use Rust nightly channel
"rust.clippy_preference": "on", // Always run Clippy lints
"rust.unstable_features": true, // Conditionally enable range formatting, not enabled by default
"rust.all_targets": false, // Don't pass `-all` to `cargo check`, it often takes too much time
```

**Comment by Tormenator1** [comment]
Ok. thanks

**Comment by dasoncheng** [comment]
settings (Ctrl + ,)  and search `crate_blacklist`, rest can fix it

**Comment by brainstorm** [comment]
> > Unknown RLS configuration: `crate_blacklist`
> 
> settings (Ctrl + ,) and search `crate_blacklist`, rest can fix it

No it doesn't. I just tried to reset via settings and the message keeps appearing after restarting VSCode:

<img width="458" alt="Skärmavbild 2019-09-23 kl  12 29 55" src="https://user-images.githubusercontent.com/175587/65399047-f053d100-ddfd-11e9-90b0-5a849c56cf56.png">

**Comment by dasoncheng** [comment]
@brainstorm 
look [rls-vscode](https://github.com/rust-lang/rls-vscode/issues/656)
> Short-term solution would be to wait a couple of days for the stable 1.38 release and prune the deprecated config entirely for now.

**Comment by brainstorm** [comment]
@dasoncheng I'm actually on insiders edition 1.39.0... so that update didn't work for me :/

![Skärmavbild 2019-09-23 kl  21 45 14](https://user-images.githubusercontent.com/175587/65423051-721e1b80-de4b-11e9-9b03-c84b8c62a93e.png)

**Comment by jice-nospam** [comment]
I've had the same message for a few weeks.
`Unknown RLS configuration: crate_blacklist`
I have no rust.crate_blacklist setting defined, in user, workspace or project configuration. Reinstalling the rls extension doesn't fix it and this error seems to block the RLS compilation. Is there some hidden system-level setting containing this parameter ?

**Comment by vuldin** [comment]
The current open ticket for this issue seems to be here: https://github.com/rust-lang/rls-vscode/issues/656

**Comment by brainstorm** [comment]
Same issue with VSCode insiders edition with 1.39 Rust :/
