### ISSUE TITLE
Way to customize colors of Structs vs Traits (etc.)?

### ISSUE THREAD

**Issue by CleanCut** [rust-lang/rls-vscode#616]
Is there a way to customize the font color and/or style for various items?  I would love to be able to try moving from IntelliJ to vscode, but at the very least I need a way to set unique colors/styles for:

- Structs
- Traits
- Enums
- Variants of enums

I figure there ought to be some way to do this with vscode config files and a rust grammar as reference, but my google skills are failing me.

**Comment by aloucks** [comment]
I don't believe RLS is providing any syntax highlighting. The default rust grammar for VSCode is here:

https://github.com/microsoft/vscode/blob/96410ff870b01dbe043cbc5f025af3ec19b8ca2e/extensions/rust/syntaxes/rust.tmLanguage.json

Enum variants can definitely be customized via themes. So can struts, traits and enums, but I think they are lumped together (with the exception of "core" traits [which are hardcoded in the grammar](https://github.com/microsoft/vscode/blob/96410ff870b01dbe043cbc5f025af3ec19b8ca2e/extensions/rust/syntaxes/rust.tmLanguage.json#L627)).
