### ISSUE TITLE
Syntax highlighting fail when using bit ops inside type parameters

### ISSUE THREAD

**Issue by ylxdzsw** [rust-lang/rls-vscode#623]
Example:

```
fn main() {
    let a = unsafe { std::mem::uninitialized::<[u8; 1<<14]>() };
    println!("{:?}", a[0])
}
```

This file is valid and can be compiled and run by `rustc`. However, vscode does not correctly render the color after `<[u8; 1<<14]>`.

![Screenshot from 2019-07-14 12-42-58](https://user-images.githubusercontent.com/7145046/61179449-08a4b400-a635-11e9-8760-8cd6164a1638.png)

expected color:

![Screenshot from 2019-07-14 12-44-24](https://user-images.githubusercontent.com/7145046/61179454-2540ec00-a635-11e9-8db3-c77a5c98f135.png)

**Comment by aloucks** [comment]
Syntax highlighting isn't (currently) provided by the RLS extension. 

https://github.com/microsoft/vscode/blob/96410ff870b01dbe043cbc5f025af3ec19b8ca2e/extensions/rust/syntaxes/rust.tmLanguage.json

**Comment by ylxdzsw** [comment]
OK, I posted it there. Thank you.
