### ISSUE TITLE
Remove Rustup dependency

### ISSUE THREAD

**Issue by TheIncorrigible1** [rust-lang/rls-vscode#655]
In an environment where I don't have admin access to my device, I cannot install Rustup, but I do have access to Cargo and whatever toolchain I need.

What would it take to remove this dependency?  I've seen #174, but the link to contributing is no longer relevant as `rust-client` options don't exist anymore.  Would it not be logical to specify paths to Cargo et al. like the `rustfmt_path` option?

**Comment by toothbrush7777777** [comment]
As far as I know, you would need a build of the Rust Language Server compatible with your compiler for a start.

**Comment by TheIncorrigible1** [comment]
@toothbrush7777777 Thanks for your feedback.  At the time I made this post, I must have had an outdated extension version because the `"rust-client.*"` options were not populating in the settings editor.  It looks like RLS is working now with Rustup disabled, but I need to fix my environment variables as it cannot find even `std`.
