### ISSUE TITLE
"failed to install rust-lang.rust"

### ISSUE THREAD

**Issue by misbell** [rust-lang/rls-vscode#667]
latest vs code as of today. macos mojave 10.14.6.

i've installed rustup, that works fine.

installed all this on catalina beta 9 yesterday with no issues.

also, when I follow instructions and download the VSIX, then click on that to install it, nothing happens. Then, attempted reinstalls of RLS produces same results (nothing)

**Comment by misbell** [comment]
ok, bit of a vscode newbie here. the extensions appear to be working, but I had to install RLS, better TOML and codeLLDB manually. Why won't my VSCode install extensions??

**Comment by misbell** [comment]
never mind, just deleted vscode and its hidden folders, then reinstalled, and it all works now.

**Comment by Xanewok** [comment]
Closing this then, thanks for the report!
