### ISSUE TITLE
Remove annoying unconditional thread::spawn snippet

### ISSUE THREAD

**Issue by OoDeLally** [rust-lang/rls-vscode#669]
The `thread::spawn` snippet seems to be suggested regardless of any context.

![image](https://user-images.githubusercontent.com/1717629/65785673-405fca00-e155-11e9-8fdb-d4938e7fbfbe.png)

There is a very *very* narrow chance I actually want to use it. it usually just pollutes my autocompletion list.

imho it should be only suggested when the user types e.g. `thsp`.

**Comment by janriemer** [comment]
I totally agree. Thanks for raising this issue. :+1:

**Comment by Xanewok** [comment]
That makes sense! Could you open a PR with that, please?
