### ISSUE TITLE
cargo not found with vscode-remote

### ISSUE THREAD

**Issue by prettynatty** [rust-lang/rls-vscode#673]
I am using vscode-remote to build project on remote Debian server.
Rustup is installed, PATH contains `~/.cargo/bin` and `cargo build` runs without problems in vscode terminal. But then I run build task from vscode I see the following error:
```
/bin/bash: cargo: command not found
```

I have `"rust-client.rustupPath": "/home/my_user/.cargo/bin/rustup"` setting in machine's settings.json (without it vscode tries to run vscode fails to find rustup using `/bin/sh` despite that `/bin/bash` is default for my user). I am using vscode 1.38.1.

**Comment by alessandrostranieri** [comment]
I have the same problem.

Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18865

**Comment by jdeepee** [comment]
Also have the same problem trying to use vs-code remote to run rls remotely on my ubuntu machine. Would be super super cool to get this resolved.

**Comment by jdeepee** [comment]
@prettynatty I just managed to fix the issue. Firstly update to 1.38.2. Secondly: create a workspace and import your folders. For some reason the moment I created a workspace RLS kicked into gear and no longer failed to start. 

All my settings are completely default and with the correct path setup for my shell it seemed to work without the need for an explicit `rustupPath`.

Interested to know if that fixes it for you.

**Comment by prettynatty** [comment]
@jdeepee Latest update fixed the problem, thanks!

**Comment by pmagwene** [comment]
I'm still experiencing this issue with Rust 1.40 and the RLS extension 0.70 on Mac OSX.

**Comment by brainstorm** [comment]
Same here, please reopen?

![Skärmavbild 2020-04-28 kl  11 52 41](https://user-images.githubusercontent.com/175587/80438131-c7bd2800-8946-11ea-9b29-baf3c5e4cdd5.png)

**Comment by weaming** [comment]
See https://github.com/rust-lang/vscode-rust/issues/675#issuecomment-623609759
