### ISSUE TITLE
How to disable automatic tasks?

### ISSUE THREAD

**Issue by silvioprog** [rust-lang/rls-vscode#693]
Hi.

I have been noticing something (cargo?) working every line I change in my source code showing the following icon in the footer of my editor:

![image](https://user-images.githubusercontent.com/1456829/67592382-f22eee00-f735-11e9-90a8-91a4cbb30a0c.png)

Is there any option to disable this? Notice I want to keep the RLS support, btw I would like to disable any automatic tasks.

Thank you!

**Comment by silvioprog** [comment]
Solved! Just put `0` in the following configuration:

![image](https://user-images.githubusercontent.com/1456829/67605121-d0dcfa80-f753-11e9-8903-8be67af17dd5.png)

**Comment by pacu** [comment]
Hi! I'm experiencing the same thing. My project is being built automatically when I run a cargo clean project. I don't want VS Code to build the project for me, since my rust code is meant to be built by my iOS project instead. I only use VS Code to edit Rust code.

**Comment by massivefermion** [comment]
nothing? this is really annoying!
I'm using Rust to make nifs for erlang and when I publish my package, the target directory should not be there!
So I have to disable the extension every single time I want to publish.
But it seems there is no option to disable the automatic builds. I tried setting Rust:jobs to zero but that didn't work.
