### ISSUE TITLE
Cargo invocation has failed: Error could not launch cargo: Error:spawn cargo ENOENT

### ISSUE THREAD

**Issue by zwhitchcox** [rust-lang/rls-vscode#708]
I'm not sure what all information I should include, but cargo debugging was working, and today it stopped for some reason.

Cargo version: cargo 1.38.0 (23ef9a4ef 2019-08-20)
VS Code version: 1.39.1
cargo path: /home/zwhitchcox/.cargo/bin/cargo

This is my `launch.json`:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "lldb",
      "request": "launch",
      "name": "Cargo test",
      "cargo": {
        "args": [
          "test",
          "--no-run",
          "--lib"
        ]
      },
      "program": "${cargo:program}",
      "args": []
    },
  {
    "type": "lldb",
    "request": "launch",
    "name": "Cargo launch",
    "cargo": {
      "args": [
        "build",
        "--lib"
      ]
    },
    "program": "${cargo:program}",
    "args": []
  }
  ]
}
```

rust settings:
```
    "rust-client.updateOnStartup": true,
    "rust.all_features": true,
```

I'm just kind of at a loss for what to do. Cargo runs fine. I can run `cargo test` or `cargo run`, but the debugger just stopped working for some reason.

**Comment by zwhitchcox** [comment]
Guess I'll get an answer to this approximately never...

**Comment by cinic** [comment]
I have a similar problem with cargo 1.48.0 on MacOS Catalina

**Comment by sebous** [comment]
I have the same problem with cargo 1.48.0 in WSL2 (Ubuntu 20.04) on windows 10 and VSCode 1.52.1

**Comment by john9631** [comment]
If someone else experiences the problem, I had it when I switched to Debian with dwm.   When I switched back to Mate as the window manager it didn't happen. 

So I tried a lot of things and two things worked:

- navigate to the project folder and open with `code .` so that's the base for this vsc instance
- add a link to cargo in a directory that just must be on vscode's path when it starts debugging

`sudo ln -s /home/your_user_name/.cargo/bin/cargo /bin/cargo`

**Comment by niconical** [comment]
> I have the same problem with cargo 1.48.0 in WSL2 (Ubuntu 20.04) on windows 10 and VSCode 1.52.1

I have the same environment. This problem occured when I deleted the target file and clicked the debug button in vscode.Here are my solutions:
- reinstall rustup on wsl2
- reopen the project with vscode(with official rust plugins) and just wait

**Comment by fradifan** [comment]
I have the same problem, but couldn't implement @john9631 solution because i can't write to my `/bin`
if you use `vadimcn.vscode-lldb` you can go to the extension setting, find `Lldb: Cargo` option, and put in the path where your cargo installation is

**Comment by ishgary** [comment]
The issue is probably with your C++ dependencies. You could update them using the Visual studio installer and for reference you could watch this out: https://www.youtube.com/watch?v=cbwGLuyvnLk
