### ISSUE TITLE
Add `<` and `>` to language-configuration.json

### ISSUE THREAD

**Issue by Luro02** [rust-lang/rls-vscode#719]
It would be quite convenient (especially with generics), if vscode would automatically insert `>` if `<` is typed (similar to what is done with `{` and `}`)

https://github.com/rust-lang/rls-vscode/blob/15f14cbcbccf8ea21dee788a013fa9a205bcb231/language-configuration.json#L12

I think adding a new item to the list would be enough? `{ "open": "<", "close": ">" }`

The plugin for atom does this too
https://github.com/rust-lang/atom-ide-rust

**Comment by dulinux** [comment]
Hello, it seems Rust language extension comes by default with autoclosing pairs on for angular brackets.

C:\Users\duli\.vscode\extensions\rust-lang.rust-0.7.4:

```
  "brackets": [
       ["{", "}"],
       ["[", "]"],
       ["(", ")"],
       ["<", ">"],
   ],
   "autoClosingPairs": [
       { "open": "{", "close": "}" },
       { "open": "[", "close": "]" },
       { "open": "(", "close": ")" },
       { "open": "<", "close": ">" },
       { "open": "\"", "close": "\"", "notIn": ["string"] },
       { "open": "/**", "close": " */", "notIn": ["string"] },
       { "open": "/*!", "close": " */", "notIn": ["string"] }
   ],

```
But it is not working. I´m currently under Windows 10.

Even if I change editor.autoClosingBrackets to "always" it still does not work. It only works for the other brackets except angular.

How can I debug this? Tks.
