### ISSUE TITLE
no_std Can't find crate for 'test'

### ISSUE THREAD

**Issue by rubberduck203** [rust-lang/rls-vscode#729]
I have a `no_std` crate that is returning this single error message.
The code builds fine.

```json
{
	"resource": "/Users/rubberduck/src/stm32f3-discovery/src/lib.rs",
	"owner": "rust",
	"code": "E0463",
	"severity": 8,
	"message": "can't find crate for `test`\n\ncan't find crate",
	"source": "rustc",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1,
	"relatedInformation": [
		{
			"startLineNumber": 1,
			"startColumn": 1,
			"endLineNumber": 1,
			"endColumn": 1,
			"message": "can't find crate",
			"resource": "/Users/rubberduck/src/stm32f3-discovery/src/lib.rs"
		}
	]
}
```

This is the contents of the `lib.rs` file that is causing the error message.

```rust
#![no_std]

pub use stm32f3xx_hal::*;
pub mod leds;
```

I found these possibly related issues (but I'm doubtful they're actually related).

- #579
- https://github.com/rust-lang/rls/issues/1409

**Comment by imjasonmiller** [comment]
Did you manage to solve this? I'm experiencing the same :-) I do notice I'm also using the `stm32f3xx_hal` crate for what it's worth.

**Comment by rubberduck203** [comment]
No luck so far @imjasonmiller, but I haven’t dug into it.

**Comment by imjasonmiller** [comment]
@rubberduck203 I solved it in my case — see the linked issue. Hopefully it is of use to you. :-)

**Comment by rubberduck203** [comment]
Confirmed works. Thanks @imjasonmiller.
Adding the following to `.vscode/settings.json` fixed it.

```json
{
    "rust.all_targets": false
}
```

**Comment by trown** [comment]
> ```json
> {
>     "rust.target": "thumbv7em-none-eabihf",
>     "rust.all_targets": false
> }
> ```

And for anyone using rust-analyzer + vscode, the settings are:
```
{
    "rust-analyzer.cargo.target": "thumbv7em-none-eabihf",
    "rust-analyzer.checkOnSave.allTargets": false
}
```
Thanks @imjasonmiller

**Comment by JohnDowson** [comment]
This solution fixes "can't find crate for 'core'" but not "for 'test'".

**Comment by andy-preston** [comment]
> ```json
> {
>     "rust.target": "thumbv7em-none-eabihf",
>     "rust.all_targets": false
> }
> ```

Sadly, this is not working for me. I'm using RLS not rust-analyzer. I'm still getting "can't find crate for `test`" on my main lib.rs file.

**Comment by duskmoon314** [comment]
> > ```json
> > {
> >     "rust.target": "thumbv7em-none-eabihf",
> >     "rust.all_targets": false
> > }
> > ```
> 
> Sadly, this is not working for me. I'm using RLS not rust-analyzer. I'm still getting "can't find crate for `test`" on my main lib.rs file.

Me too. I'm getting this on my main.rs.

**Comment by ritsource** [comment]
```json
"rust-analyzer.cargo.target": "x86_64-unknown-none",
"rust-analyzer.checkOnSave.allTargets": false,
```

```json
"rust.target": "x86_64-unknown-none",
"rust.all_targets": false,
```

**Comment by YoshieraHuang** [comment]
> > ```json
> > {
> >     "rust.target": "thumbv7em-none-eabihf",
> >     "rust.all_targets": false
> > }
> > ```
> 
> Sadly, this is not working for me. I'm using RLS not rust-analyzer. I'm still getting "can't find crate for `test`" on my main lib.rs file.

Me too. I wonder that it may need another equivelant settings to this in `rust-analyzer`:
```json
{
    "rust-analyzer.checkOnSave.extraArgs": [
        "--bins"
    ],
}
```

**Comment by asukiaaa** [comment]
I cannot resolve error `can't find crate for `test`` on rust plugin on VSCode.

![Screenshot from 2021-12-25 18-34-09](https://user-images.githubusercontent.com/5975178/147382316-b860c61a-f5c4-4976-9d4c-843a194e160f.png)

However I could resolve it with using rust-analyzer plugin on VSCode.
Ref https://github.com/rust-analyzer/rust-analyzer/issues/3801

![Screenshot from 2021-12-25 18-34-43](https://user-images.githubusercontent.com/5975178/147382315-14691ac8-2784-495f-810b-1aa9e2c21149.png)

I think that configuration for rust-analyzer via the rust-plugin.
Is there any option to resolve the error on the rust-plugin plugin?
(For each actions, I reload the window of VSCode.)

**Comment by lnicola** [comment]
@asukiaaa if rust-analyzer works, do you have any reason to avoid it?

**Comment by asukiaaa** [comment]
I can use rust-analyzer plugin with disabling rust-plugin (this plugin) but what the meaning of presence for rust-plugin?

**Comment by lnicola** [comment]
rust-analyzer will sooner or later replace RLS (and the Rust extension), see also https://github.com/rust-lang/vscode-rust/issues/927.

**Comment by asukiaaa** [comment]
I see, thank you for the information.

**Comment by rishadbaniya** [comment]
For people using rust analyzer with coc and neovim, look for coc-settings.json in google for rust analyzer and fill those attributes

**Comment by shenshouer** [comment]
> Confirmed works. Thanks @imjasonmiller. Adding the following to `.vscode/settings.json` fixed it.
> 
> ```json
> {
>     "rust.target": "thumbv7em-none-eabihf",
>     "rust.all_targets": false
> }
> ```

not worked for me ~

**Comment by shenshouer** [comment]
> Confirmed works. Thanks @imjasonmiller. Adding the following to `.vscode/settings.json` fixed it.
> 
> ```json
> {
>     "rust.target": "thumbv7em-none-eabihf",
>     "rust.all_targets": false
> }
> ```

not worked for me ~

**Comment by pluveto** [comment]
Not working
```
{
    "rust.target": "riscv64gc-unknown-none-elf",
    "rust.all_targets": false,
}
```

**Comment by cjm571** [comment]
Ran into this same issue and was able to fix it by adding the following to my `Cargo.toml`:
```
[[bin]]
name = "app"
test = false
bench = false
```

**Comment by BRA1L0R** [comment]
Solution for **rust-analyzer**

Add these lines in `.vscode/settings.json`:
```json
{
    "rust-analyzer.cargo.target": "thumbv7em-none-eabihf",
    "rust-analyzer.checkOnSave.allTargets": false,
}
```
