### ISSUE TITLE
Couldn't use the extension if I'm in a remote development environment.

### ISSUE THREAD

**Issue by Kellermaan** [rust-lang/rls-vscode#773]
Hi,
I'm trying to develop rust program on my server just like I use C language on my server with the remote development extension. But I find out the rls extension doesn't work on my case. I'm wondering if rls is not supported in remote development, or I just missed something.

Thanks!

**Comment by Xanewok** [comment]
Thanks for the report! Do you refer to the [Remote - SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) workflow?

**Comment by Kellermaan** [comment]
@Xanewok Yes, The rls doesn't work when I use the Remote-ssh workflow.

**Comment by Xanewok** [comment]
Could you try using latest 0.7.4 version of the extension and see if it
works?

**Comment by Kellermaan** [comment]
Now it can work, but sometimes it show this: The Rust Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.
