### ISSUE TITLE
Include `use std::thread;` in code template for spawning a thread

### ISSUE THREAD

**Issue by abd45** [rust-lang/rls-vscode#787]
While generating `thread::spawn`  block, please also generate `use std::thread;`. Otherwise, the template generation is incomplete.

**Comment by Xanewok** [comment]
Closesd by https://github.com/rust-lang/rls-vscode/commit/79410f6a091071da086aa789c0f66c85fdd9b5ea, which automatically adds the full path in the snippet. We don't have the path resolution knowledge at the time of snippet inserting so we can't make a decision whether we need to use `std` or even `std::thread` at all, so we just insert the full path and let the user decide.

**Comment by abdasgupta** [comment]
Thanks @Xanewok . That will do.
