### ISSUE TITLE
Unknown RLS configuration: `rust_analyzer`

### ISSUE THREAD

**Issue by shuaixr** [rust-lang/rls-vscode#794]
extended version:0.7.6
vscode version:1.45
rustc --version
rustc 1.45.0-nightly (769d12eec 2020-05-12)

0.7.5 will not have this problem
Please let me know if you need other parameters

**Comment by Xanewok** [comment]
Should be fixed in 0.7.7 (https://github.com/rust-lang/rls-vscode/commit/5f132862baf199bdd1aa4f4f816de6a49c5b7254). Sorry about that, it seems that a commit has been lost while I worked on the RLS/rust-analyzer engine support!
