### ISSUE TITLE
Feature Suggestion: supply description, latest-version for Cargo.toml

### ISSUE THREAD

**Issue by chriskrycho** [rust-lang/rls-vscode#92]
This is *way* down the priority list, but I thought of it so I figured I'd put it here.

When you open a package.json file, you can hover over a dependency and it lists the short description and the latest version available for that package:

<img width="629" alt="hover" src="https://user-images.githubusercontent.com/2403023/28414687-d7d043e4-6d1a-11e7-8892-6b864c13ac57.png">

Adding this same functionality to this add-on for Cargo.toml files would be 💯 😍. Again: super low on the priority list, but a very nice-to-have feature.

**Comment by nrc** [comment]
Agree this would be great to have!

**Comment by kjeremy** [comment]
For reference I believe the equivalent functionality for package.json is implemented in https://github.com/Microsoft/vscode/blob/master/extensions/javascript/src/features/packageJSONContribution.ts

**Comment by softprops** [comment]
Not sure if this exactly want you want but I've found https://marketplace.visualstudio.com/items?itemName=serayuzgur.crates to be useful in letting me know when I'm behind on crate versions and let's me know what the latest is

**Comment by Xanewok** [comment]
I think we'd like to keep things lean here and rely on the external extension ([crates](https://marketplace.visualstudio.com/items?itemName=serayuzgur.crates) is great, I've been using it myself!) instead, so I'll close this issue.
