### ISSUE TITLE
[dev-dependencies] are not taken into account 

### ISSUE THREAD

**Issue by rohel01** [rust-lang/rls-vscode#99]
Fedora 25 x86_64
VSCode 1.14.2
Rust (rls) 0.1.0

Rust toolchain installed with rustup and up to date.

Dependencies added in the [dev-dependencies] section of the Cargo.toml are not picked up by the Rust (rls) extension. I get the following error 

```
severity: 'Error'
message: 'use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, and unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)'
at: '7,1'
source: 'rustc'
```

If I move the dependency in the [dependencies] section and restart VScode (see #98), the error goes away.

**Comment by nrc** [comment]
cc https://github.com/rust-lang-nursery/rls/issues/169

**Comment by Xanewok** [comment]
This works as expected and was fixed with https://github.com/rust-lang/rls/pull/801.

**Comment by phra** [comment]
is this happening again?

![image](https://user-images.githubusercontent.com/984628/59311476-eae8d580-8ca9-11e9-92ed-0c0bf773a564.png)
